# Generated by Django 2.0 on 2018-08-02 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0002_chatperguntavaga_respondida'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPerguntaResp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaga_id', models.IntegerField()),
                ('cand_id', models.IntegerField()),
                ('resposta', models.CharField(max_length=200)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.ChatPerguntaVaga')),
            ],
            options={
                'db_table': 'chat_pergunta_resp',
            },
        ),
    ]
