# -*- coding:utf-8 -*-
icones = {
    'user': 'fa-user',
    'users': 'fa fa-users',
    'user-plus': 'fa fa-user-plus',
    'meta': 'fa-crosshairs',
    'avaliacao': 'fa-address-card-o',
    'feedback': 'fa-address-book',
    'email':'fa-envelope-open-o',
    'email_close':'fa fa-envelope',
    'comunicacao': 'fa-comments',
    'aniversario': 'fa-birthday-cake',
    'calendario': 'fa-calendar',
    'relatorio': 'fa-pie-chart',
    'zoom_in': 'glyphicon glyphicon-zoom-in',
    'zoom_out': 'glyphicon glyphicon-zoom-out',
    'rotate_left': 'fa-rotate-left',
    'rotate_right': 'fa-rotate-right',
    'configuracao': 'fa-cogs',
    'noticias': 'fa-newspaper-o',
    'cadastro': 'fa-file-text-o',
    'search-plus': 'fa-search-plus',
    'list': 'fa-list',
    'list_alt': 'fa-list-alt',
    'area_chart': 'fa-area-chart',
    'line-chart': 'fa-line-chart',
    'bar-chart': 'fa fa-bar-chart',
    'home': 'fa-home',
    'save':'fa fa-floppy-o',
    'edit':'fa fa-edit',
    'delete':'fa fa-trash-o',
    'detalhes':'fa fa-eye',
    'filtrar':'fa fa-search',
    'aprovar':'fa fa-check',
    'anexo': 'fa-paperclip',
    'download':'fa fa-download',
    'enviar_email': 'linecons-mail',
    'adicionar':'fa fa-plus',
    'fechar':'fa fa-close',
    'exclamacao':'fa fa-exclamation',
    'clock':'fa fa-clock-o',
    'organograma':'fa fa-sitemap',
    'search': 'fa-search',
    'calendar': 'fa-calendar',
    'comment':'linecons-comment',
    'pencil':'fa-pencil',
    'check_square':'fa-check-square',
    'nocheck_square':'fa-square-o',
    'link':'fa-link',
    'plus_circle':'fa fa-plus-circle',
    'minus_circle':'fa-minus-circle',
    'positivo':'glyphicon glyphicon-thumbs-up',
    'negativo':'glyphicon glyphicon-thumbs-down',
    'book':'fa-book',
    'cap':'fa-graduation-cap',
    'star_half':'fa-star-half-o',
    'key':"fa-key",
    'print': 'fa-print',
    'star': 'fa fa-star',
    'recycle': 'fa fa-recycle',
    'file': 'fa-file',
    'lock': 'fa-lock',
    'question-circle': 'fa-question-circle',
    'info': 'fa-info-circle',
    'voltar': 'fa-arrow-left',
    'male': 'fa fa-male',
    'curriculo': "fa fa-file-photo-o",
    'cv_padrao': "fa fa-file-text",
    'deficiencia': 'fa fa-wheelchair',
    'visualizado': 'fa fa-check-square-o',
    'limpar': 'fa fa-refresh',
    'cliente': 'fa fa-building',
    'vaga': 'fa fa-briefcase',
    'selecao_candidatos': 'fa fa-bullseye',
    'candidato': 'fa fa-male',
    'fila_selecao': 'fa fa-indent',
    'encerrar_contrato': 'fa fa-scissors',
    'mov_funcional': 'fa fa-repeat',
    'localizacao': 'fa fa-map-marker',
    'a': 'fa fa-font',
    'picture': 'fa fa-picture-o',
    'remover': 'fa fa-remove',
    'minus': 'fa fa-minus',
    'manutencao': 'fa fa-gears',
    'comercial': 'fa-phone-square',
    'taxa': 'fa-dollar',
    'upload': 'fa fa-folder-open',
    'upload_cv': 'fa fa-upload',
    'upload_doc': 'fa fa-upload',
    'webcam': 'fa fa-camera',
    'sms': 'fa fa-mobile-phone',
    'servico': 'fa fa-gavel',
    'encaminhamento': 'linecons-paper-plane',
    'copia': 'fa fa-copy',
}
