# -*- coding:utf-8 -*-
from django.utils.translation import ugettext as _

textos_a = {
    'a_combinar': _(u'A combinar'),

    'aberta': _(u'Aberta'),
    'abertas': _(u'Abertas'),
    'abertura_vaga': _(u'Abertura de Vaga'),
    'abertura_vaga_sucesso': _(u'Abertura de Vaga realizada com sucesso.'),
    'abertura_vaga_instrucao': _(u"Preencha os dados abaixo para abrir a vaga"),
    'abril': _(u'Abril'),
    'abrir_requisicao_vaga': _(u'Abrir Requisição de Vaga'),
    'abrir_foto': _(u'Abrir Foto'),
    'abrir_imagem': _(u'Abrir Imagem'),
    'abrir_link': _(u'Abrir Link'),
    'abrir_logo': _(u'Abrir Logo'),

    'acao': _(u'Ação'),
    'acoes': _(u'Ações'),
    'aceita_divulgacao_vaga': _(u"Desejo receber via e-mail informações sobre novas vagas compatíveis com o meu perfil cadastrado"),
    'aceita_temp': _(u'Aceita Temporário?'),
    'aceita_termos': _(u'Eu li e aceitei os termos e condições'),
    'aceita_termos_usoimagem': _(u'Eu li e aceitei os termos e condições'),
    'aceita_turno': _(u'Aceita Turno?'),
    'acessar_cliente': _(u'Acessar Cliente'),
    'acesse_portal': _(u'Acesse o Portal'),
    'acesse_portal_candidato': _(u'Acesse o Portal do Candidato'),
    'acesse_portal_cliente': _('Acesse o Portal do Cliente'),
    'acesso_sistema': _(u'Acesso - Sistema'),
    'acesso_enviado': _(u'Acesso enviado.'),
    'acesso_portal_cliente': _(u'Acesso para o Portal do Cliente'),
    'achaempregos': _(u'AchaEmpregos'),

    'adiar_aviso': _(u'Adiar Aviso'),
    'adiar_em': _(u'Adiar em'),
    'adiantamento_compromisso': _(u'Adiamento de Compromisso'),
    'adiantamento_compromisso_instrucao': _(u'Tem certeza de que deseja adiar a Notificação para esse Compromisso?'),
    'adiantamento_compromisso_sucesso': _(u'Aviso adiado.'),
    'adiantamento_compromisso_erro': _(u'Houve um erro ao adiar a Notificação para esse Compromisso.'),
    'adicional_noturno':  _(u'Adicional Noturno'),
    'adicionar': _(u'Adicionar'),
    'adicionar_colaborador': _(u'Adicionar Colaborador'),
    'adicionar_candidato': _(u'Adicionar Candidato'),
    'adicionar_parecer': _(u'Adicionar Novo Parecer'),
    'adicionar_produto': _(u'Adicionar Novo Produto'),
    'adiministrador_aviso': _(u"Usuário membro do grupo de Administradores. Mesmo sem as permissões concedidas, este usuário tem acesso a todo o sistema."),

    'ainda_n_cadastrado': _(u'Ainda não é cadastrado?'),

    'agencia': _(u'Agência'),
    'agenda_compromisso': _(u'Agenda de Compromissos'),
    'agenda_compromisso_descricao': _(u'Crie e gerencie compromissos para você e outros usuários.'),
    'agenda_compromisso_novo': _(u'Novo Compromisso'),
    'agendar_compromisso_para': _(u'Agendar Compromisso para'),
    'agosto': _(u'Agosto'),
    'aguardando_validacao': _(u'Aguardando Validação'),

    'ajuda': _(u'Ajuda'),

    'album_fotos': _(u'Álbum de Fotos'),
    'alerta': _(u'Alerta'),
    'alguns_clientes': _(u'Alguns de Nossos Clientes'),
    'alta': _(u'Alta'),
    'alterar_promotor': _(u'Alterar Promotor'),
    'alternativa': _(u'Alternativa'),
    'alternativas': _(u'Alternativas'),
    'alternativa_duplicada': _(u'Esta alternativa já foi selecionado anteriormente.'),
    'alternativa_sucesso': _(u'Alternativa salva com sucesso.'),
    'alternativas_n_preenchidos': _(u'Existem alternativas não preenchidas. Para adicionar outras, preencha primeiro as adicionadas.'),
    'alteracao': _(u"Alteração"),
    'alteracao_data_hora': _(u'Alteração de Data/ Hora'),
    'alteracao_data_compromisso_confirmar': _(u'Deseja realmente mudar o Período desse Compromisso?'),
    'alteracao_data_compromisso_sucesso': _(u'Período do Compromisso alterado.'),
    'alteracao_data_compromisso': _(u'Alteração de Data de Compromisso'),
    'altura': _(u'Altura'),
    'altura_maxima': _(u"Altura Máxima"),
    'altura_minima': _(u"Altura Mínima"),
    'altura_minimo_menor_altura_maximo': _(u'A Altura Mínima deve ser menor que a Altura Máxima.'),
    'alteracao_conceito': _(u'Alteração de Conceito de Candidato'),

    'ambos': _(u'Ambos'),

    'analise_vaga': _(u'Análise de Vagas'),
    'anexar_imagem': _(u"Anexar Imagem"),
    'anexar_documento': _(u'Anexar Documento'),
    'anexo': _(u'Anexo'),
    'anexos': _(u'Anexos'),
    'anexo_candidato': _(u'Anexo do Candidato'),
    'anexo_candidato_nao_encontrado': _(u'O Anexo do Candidato não foi encontrado.'),
    'anexo_invalido_formato': _(u'Formato do anexo está inválido. Tipos de arquivos permitidos: %s.'),
    'anexo_invalido_type_error': _(u"É necessário colocar a extensão no arquivo."),
    'anexo_invalido_size_error': _(u"O arquivo deve ter no máximo"),
    'anexo_invalido_virus_error': _(u"O arquivo pode estar infectado com vírus. Insira outro arquivo."),
    'anexo_somente': _(u'Somente com anexo'),
    'anexo_vaga': _(u'Anexo da Vaga'),
    'anexos_observacao': _(u'Anexos - Observação'),
    'anexos_vaga': _(u'Anexos da Vaga'),
    'anexo_removido': _(u'Anexo removido com sucesso.'),
    'aniversario': _(u"Aniversário"),
    'aniversario_ini': _(u"Aniversário Inicial"),
    'aniversario_fin': _(u"Aniversário Final"),
    'aniversario_dm': _(u"Aniversário(dd/mm)"),
    'aniversarios_contatos_cliente': _(u'Aniversários de Contatos dos Clientes'),
    'aniversariantes_do_dia': _(u'Aniversariantes do dia'),
    'ano_conclusao': _(u'Ano Conclusão'),
    'anunciante': _(u'Anunciante'),
    'anterior': _(u'Anterior'),

    'apenas_numeros': _(u'Apenas Números'),
    'aprovado': _(u"Aprovado"),
    'aprovada': _(u"Aprovada"),
    'aprovacao': _(u"Aprovação"),
    'aprovar_candidato': _(u"Aprovar Candidato"),
    'aprovar_candidato_confirma': _(u"Deseja realmente aprovar o Candidato?"),
    'aprovar_candidato_sucesso': _(u"Candidato aprovado com sucesso."),
    'aprovar_candidato_remover': _(u"Remover Aprovação"),
    'aprovar_candidato_remover_confirma': _(u"Deseja realmente remover a Aprovação do Candidato?"),
    'aprovar_candidato_remover_sucesso': _(u"A Aprovação do Candidato foi removida com sucesso."),
    'apenas_numeros': _(u"Apenas números"),

    'areafuncao': _(u'Área da Função'),
    'areasfuncao': _(u'Áreas da Função'),
    'areafuncao_duplicada': _(u"Já existe uma Àrea da Função com essa descrição."),
    'areafuncao_duplicada_sigla': _(u"Já existe uma Àrea da Função com essa sigla."),
    'areafuncao_nao_encontrada': _(u'A Área da Função não foi encontrada.'),
    'areafuncao_sucesso': _(u"A Área da Função foi salva com sucesso."),
    'arquivo_invalido': _(u"Arquivo em formato inválido."),
    'arquivo_pronto': _(u'Arquivo pronto'),
    'arquivo_obrigatorio': _(u'Arquivo obrigatorio.'),
    'arquivos_gerados_sucesso': _(u'Arquivos gerados com sucesso'),

    'assinatura_premium': _(u'Assinatura Premium'),
    'assunto': _(u'Assunto'),

    'atencao': _(u'Atenção'),
    'atividade': _(u'Atividade'),
    'atividades_exercidas': _(u'Atividades Exercidas'),
    'ativo': _(u'Ativo'),
    'ativar_cand_portal': _(u'Deseja habilitar a opção de ativar o candidato quando\
                    o mesmo atualizar seu currículo no portal do candidato?'),
    'atual': _(u'Atual'),
    'atualmente': _(u'Atualmente'),
    'atualizar': _(u'Atualizar'),
    'atualizado_a': _(u'Atualizado a'),
    'atualizado_candidato': _(u"Atualizado pelo Candidato"),
    'atraso_de': _(u'Atraso de'),
    'ate_a_data': _(u"Até a data"),

    'audio': _(u'Audio'),
    'auditiva': _(u'Auditiva'),

    'avisar_antes_de': _(u'Avisar com antecedência de'),
    'avisar_antes_de_inválido': _(u'"Avisar com antecedência de" inválido.'),
    'avisar_novamento_em': _(u'Avisar novamento em'),
    'avisos': _(u'Avisos'),
    'avisos_alertas_sistema': _(u'Avisos ou Alertas do Sistema'),
    'aviso_alerta_sistema_nao_encontrado': _(u'O Aviso ou Alerta do Sistema não foi encontrado.'),
    'aviso_alerta_sistema_sucesso': _(u"Aviso ou Alerta do Sistema foi salvo com sucesso."),
}
