# -*- coding:utf-8 -*-
from django.utils.translation import ugettext as _

textos_b = {
    'baixar_anexo': _(u'Baixar Anexo'),
    'baixar_arquivo': _(u'Baixar Arquivo'),
    'baixar_curriculo_anexo': _(u'Baixar Currículo Anexo'),
    'baixar_imagem_curriculo_anexo': _(u'Baixar Imagem do Currículo Anexo'),
    'bairro': _(u'Bairro'),
    'bairro_cobr': _(u'Bairro Cobr.'),
    'baixa': _(u'Baixa'),
    'banco': _(u'Banco'),
    'banner': _(u'Banner'),
    'base_de_dados': _(u'Base de Dados'),
    'base_de_dados_selecao_trocar': _(u'Deseja realmente trocar a Base de Dados da Seleção? Caso não tenha salvo a seleção, irá perder o progresso.'),
    'beneficio': _(u'Benefício'),
    'beneficios': _(u'Benefícios'),
    'beneficio_cliente_sucesso': _(u'O Benefício do Cliente foi salvo com sucesso.'),
    'beneficio_cliente_nao_encontrado': _(u'O Benefício do Cliente não foi encontrado.'),
    'beneficio_cliente_duplicado':_(u"O Benefício escolhido já foi salvo para esse Cliente."),
    'beneficio_vaga': _(u'Benefício da Vaga'),
    'beneficios_vagas': _(u'Benefícios da Vaga'),
    'beneficio_vaga_sucesso': _(u'O Benefício da Vaga foi salvo com sucesso.'),
    'beneficio_vaga_nao_encontrado': _(u'O Benefício da Vaga não foi encontrado.'),
    'beneficio_vaga_duplicado':_(u"O Benefício escolhido já foi salvo para essa Vaga."),
    'beneficio_duplicado': _(u"Já existe um Benefício com essa descrição."),
    'beneficio_nao_encontrado': _(u'O Benefício não foi encontrado.'),
    'beneficio_sucesso': _(u"O Benefício foi salvo com sucesso."),
    'bne': _(u"BNE"),
    'banner': _(u"Banner"),
    'banners': _(u"Banners"),
    'banners_do_portal': _(u"Banners do Portal"),
    'banners_instrucao': _(u"""Ao inserir os banners clique no botão Salvar para realizar a alteração.<br/>\
             O Banner deve ter o tamanho de 610x160 e até 100Kb."""),
    'banner1pagseguro_alteracao_erro': _(u"Banner 1 do PagSeguro não foi salvo"),
    'banner2pagseguro_alteracao_erro': _(u"Banner 2 do PagSeguro não foi salvo"),
    'banner1pagseguro_alteracao': _(u"Alteração do Banner 1 do PagSeguro."),
    'banner2pagseguro_alteracao': _(u"Alteração do Banner 2 do PagSeguro."),
    'banner_excluir': _(u"Deseja realmente excluir o banner?"),
    'banner1_alteracao_erro': _(u"Banner 1 não foi salvo."),
    'banner2_alteracao_erro': _(u"Banner 2 não foi salvo."),
    'banner3_alteracao_erro': _(u"Banner 3 não foi salvo."),
    'banner1_alteracao': _(u"Alteração do Banner 1."),
    'banner2_alteracao': _(u"Alteração do Banner 2."),
    'banner3_alteracao': _(u"Alteração do Banner 2."),
    'bonus': _(u'Bônus'),
    'busca_vagas': _(u'Busca de Vagas'),
    'bloquear_login_fora_horario': _(u'Ativar o Bloqueio de Login fora do Horário Comercial.'),
    'bloquear_login_fora_horario_msg': _(u'O Sistema só pode ser acessado das {} às {}.'),
}
