from django.utils.translation import ugettext as _

textos_c = {
    'cadastro': _(u'Cadastro'),
    'cadastros': _(u'Cadastros'),
    'cadastrar_novo': _(u'Cadastrar Novo'),
    'cadastrar_nova': _(u'Cadastrar Nova'),
    'cadastro_nao_editaexclui': _(u'Este cadastro não pode ser editado ou excluído.'),
    'cadastrado_desde': _(u'Cadastrado Desde'),
    'cadastre_curriculo': _(u'Cadastre seu Currículo'),
    'cadastro_completo': _(u'Cadastro Completo'),
    'cad_areafuncao': _(u'Cadastro da Área da Função'),
    'cad_areafuncao_novo': _(u'Cadastre aqui uma nova Área da Função'),
    'cad_anexo_cand': _(u'Cadastro de Anexo do Candidato'),
    'cad_auxiliares': _(u'Cadastros Auxiliares'),
    'cad_auxiliares_cliente': _(u'Cadastros Auxiliares do Cliente'),
    'cad_auxiliares_candidato': _(u'Cadastros Auxiliares do Candidato'),
    'cad_auxiliares_funcao': _(u'Cadastros Auxiliares da Função'),
    'cad_auxiliares_vaga': _(u'Cadastros Auxiliares do Perfil da Vaga'),
    'cad_auxiliares_outros': _(u'Cadastros Auxiliares de Outros'),
    'cad_aviso_alerta': _(u'Cadastro de Avisos ou Alertas'),
    'cad_aviso_alerta_novo': _(u'Cadastre aqui um novo Aviso ou Alerta do Sistema'),
    'cad_beneficio': _(u'Cadastro de Benefício'),
    'cad_beneficio_novo': _(u'Cadastre aqui um novo Benefício.'),
    'cad_candidato': _(u'Cadastro de Candidato'),
    'cad_candidato_novo': _(u'Cadastre aqui um novo Candidato'),
    'cad_cliente': _(u'Cadastro de Cliente'),
    'cad_cliente_novo': _(u'Cadastre aqui um novo Cliente.'),
    'cad_cliente_beneficio': _(u'Cadastro de Benefício do Cliente'),
    'cad_cliente_contato': _(u'Cadastro de Contato do Cliente'),
    'cad_cliente_controle_acesso': _(u'Cadastro de Controle de Acesso'),
    'cad_cliente_ocorrencia': _(u'Cadastro de Ocorrência do Cliente'),
    'cad_cliente_proposta': _(u'Cadastro de Proposta do Cliente'),
    'cad_cliente_servico': _(u'Cadastro de Serviço do Cliente'),
    'cad_cliente_taxa': _(u'Cadastro de Taxa do Cliente'),
    'cad_cliente_taxavaga': _(u'Cadastro de Taxa da Vaga do Cliente'),
    'cad_conceito': _(u'Cadastro de Conceito de Candidato'),
    'cad_conceito_novo': _(u'Cadastre aqui um novo Conceito de Candidato.'),
    'cad_conhec_hab_cand': _(u'Cadastro de Conhecimentos/Habilidades do Candidato'),
    'cad_conhec_hab_vaga': _(u'Cadastro de Conhecimentos/Habilidades do Perfil da Vaga'),
    'cad_ct': _(u'Cadastro de Habilidade Técnica'),
    'cad_ct_nova': _(u'Cadastre aqui uma nova Habilidade Técnica.'),
    'cad_deficiencia': _(u'Cadastro de Deficiência'),
    'cad_deficiencia_novo': _(u'Cadastre aqui uma nova Deficiência.'),
    'cad_documentoimpressao': _(u'Cadastro de Documento para Impressão'),
    'cad_documentoimpressao_novo': _(u'Cadastre aqui um novo Documento para Impressão.'),
    'cad_escalact': _(u'Cadastro de Escala de Habilidade Técnica'),
    'cad_escalact_nova': _(u'Cadastre aqui uma nova Escala de Habilidade Técnica'),
    'cad_escolaridade': _(u'Cadastro de Escolaridade'),
    'cad_escolaridade_nova': _(u'Cadastre aqui uma nova Escolaridade.'),
    'cad_estadocivil': _(u'Cadastro de Estado Civil'),
    'cad_estadocivil_novo': _(u'Cadastre aqui um novo Estado Civil.'),
    'cad_etapaprocsel': _(u'Cadastro de Etapa de Processo Seletivo'),
    'cad_etapaprocsel_nova': _(u'Cadastre aqui uma nova Etapa de Processo Seletivo'),
    'cad_etnia': _(u'Cadastro de Etnia'),
    'cad_etnia_novo': _(u'Cadastre aqui uma nova Etnia.'),
    'cad_experiencia_cand': _(u'Cadastro de Experiencia Profissional do Candidato'),
    'cad_familiact': _(u'Cadastro de Família de Habilidade Técnica'),
    'cad_familiact_novo': _(u'Cadastre aqui uma nova Família de Habilidade Técnica.'),
    'cad_filial': _(u'Cadastro de Filial'),
    'cad_filial_nova': _(u'Cadastre aqui uma nova Filial.'),
    'cad_funcao': _(u'Cadastro de Função'),
    'cad_funcao_novo': _(u'Cadastre aqui uma nova Função.'),
    'cad_formapagto': _(u'Cadastro de Forma de Pagamento'),
    'cad_formapagto_nova': _(u'Cadastre aqui uma nova Forma de Pagamento'),
    'cad_grupoempresa': _(u'Cadastro de Grupo de Empresa'),
    'cad_grupoempresa_novo': _(u'Cadastre aqui um novo Grupo de Empresa.'),
    'cad_grupousuario': _(u'Cadastro de Grupo de Usuário'),
    'cad_grupousuario_novo': _(u'Cadastre aqui um novo Grupo de Usuário.'),
    'cad_historicoocorrencia': _(u'Cadastro de Histórico de Ocorrência'),
    'cad_historicoocorrencia_novo': _(u'Cadastre aqui um novo Histórico de Ocorrência.'),
    'cad_histperfilvaga': _(u'Cadastro de Histórico de Perfil de Vaga'),
    'cad_histperfilvaga_novo': _(u'Cadastre aqui um novo Histórico de Perfil de Vaga.'),
    'cad_idioma': _(u'Cadastro de Idioma'),
    'cad_idioma_novo': _(u'Cadastre aqui um novo Idioma.'),
    'cad_institutoensino': _(u'Cadastro de Instituto de Ensino'),
    'cad_institutoensino_novo': _(u'Cadastre aqui um novo Instituto de Ensino.'),
    'cad_motivoabertura': _(u'Cadastro de Motivo de Abertura de Vaga'),
    'cad_motivoabertura_novo': _(u'Cadastre aqui um novo Motivo de Abertura de Vaga.'),
    'cad_motivo_alteracao_status': _(u'Cadastro de Motivo de Manutenção de Status da Vaga'),
    'cad_motivo_alteracao_status_novo': _(u'Cadastre aqui um novo Motivo de Manutenção de Status da Vaga.'),
    'cad_multiportal': _(u'Cadastro Múltiplos Portais do Candidato'),
    'cad_multiportal_novo': _(u'Cadastre aqui um novo Portal do Candidato.'),
    'cad_nacionalidade': _(u'Cadastro de Nacionalidade'),
    'cad_nacionalidade_nova': _(u'Cadastre aqui uma nova Nacionalidade.'),
    'cad_nivelexperiencia': _(u'Cadastro de Tempo/Nível de Experiência'),
    'cad_nivelexperiencia_novo': _(u'Cadastre aqui um novo Tempo/Nível de Experiência.'),
    'cad_nivelhierarquico': _(u'Cadastro de Nível Hierárquico'),
    'cad_nivelhierarquico_novo': _(u'Cadastre aqui um novo Nível Hierárquico.'),
    'cad_obstipovaga': _(u'Cadastro de Observação do Tipo de Vaga'),
    'cad_obstipovaga_nova': _(u'Cadastre aqui uma nova Observação do Tipo de Vaga.'),
    'cad_origem': _(u'Cadastro de Origem de Candidato'),
    'cad_origem_nova': _(u'Cadastre aqui uma nova Origem de Candidato.'),
    'cad_pais': _(u'Cadastro de País'),
    'cad_pais_novo': _(u'Cadastre aqui um novo País.'),
    'cad_parecer_cand': _(u'Cadastro de Parecer do Candidato'),
    'cad_portecliente': _(u'Cadastro de Porte do Cliente'),
    'cad_portecliente_novo': _(u'Cadastre aqui um novo Porte do Cliente.'),
    'cad_principal' : _(u'Cadastros Principais'),
    'cad_produtocliente': _(u'Cadastro de Produto que o Cliente Consome'),
    'cad_produtocliente_novo': _(u'Cadastre aqui um novo Produto que o Cliente Consome.'),
    'cad_questionario_vaga': _(u'Cadastro do Questionário do Perfil da Vaga'),
    'cad_ramoatividade': _(u'Cadastro de Ramo de Atividade'),
    'cad_ramoatividade_novo': _(u'Cadastre aqui um novo Ramo de Atividade.'),
    'cad_recrutador': _(u'Cadastro de Recrutador'),
    'cad_recrutador_novo': _(u'Cadastre aqui um novo Recrutador.'),
    'cad_religiao': _(u'Cadastro de Religião'),
    'cad_religiao_nova': _(u'Cadastre aqui uma nova Religião.'),
    'cad_relacao': _(u'Cadastro de Relação'),
    'cad_relacao_novo': _(u'Cadastre aqui os tipos de vínculos possíveis de relacionar uma pessoa a indivíduos do seu grupo familiar. (Ex. Pai, Filho, Tio, Primo...).'),
    'cad_simplificado': _('Cadastro Simplificado'),
    'cad_sms': _(u'Cadastro de Mensagem de SMS'),
    'cad_sms_novo': _(u'Cadastre aqui uma nova Mensagem de SMS.'),
    'cad_sms_listagem': _(u'Lista todas as mensagens de sms cadastradas.'),
    'cad_statuscliente': _(u'Cadastro de Status do Cliente'),
    'cad_statuscliente_novo': _(u'Cadastre aqui um novo Status do Cliente.'),
    'cad_tamanhovestuario': _(u'Cadastro de Tamanho de Vestuário'),
    'cad_tamanhovestuario_novo': _(u'Cadastre aqui um novo Tamanho de Vestuário.'),
    'cad_testes_online': _(u'Cadastro de Teste on-line'),
    'cad_testes_online_novo': _(u'Cadastre aqui um novo Teste on-line.'),
    'cad_tipocandidato': _(u'Cadastro de Tipo de Candidato'),
    'cad_tipocandidato_novo': _(u'Cadastre aqui um novo Tipo de Candidato.'),
    'cad_tipocliente': _(u'Cadastro de Tipo de Cliente'),
    'cad_tipocliente_novo': _(u'Cadastre aqui um novo Tipo de Cliente.'),
    'cad_tipodocumento': _(u'Cadastro Tipo de Documento'),
    'cad_tipodocumento_novo': _(u'Cadastre aqui um novo Tipo de Documento.'),
    'cad_tipovaga': _(u'Cadastro de Tipo de Vaga'),
    'cad_tipovaga_novo': _(u'Cadastre aqui um novo Tipo de Vaga.'),
    'cad_usuario': _(u'Cadastro de Usuário'),
    'cad_usuario_novo': _(u'Cadastre aqui um novo Usuário.'),
    'cad_vaga': _(u'Cadastro de Perfil da Vaga'),
    'cad_vaga_anexo': _(u'Cadastro de Anexo de Perfil da Vaga'),
    'cad_vaga_beneficio': _(u'Cadastro de Benefício do Perfil da Vaga'),
    'cad_vaga_novo': _(u'Cadastre aqui um novo Perfil da Vaga.'),
    'cad_vaga_simplificado': _(u'Cadastro de Perfil da Vaga Simplificado'),
    'cad_vaga_impossivel': _(u'Não foi possível cadastrar a vaga.'),
    'cad_vaga_sucesso': _(u'Vaga cadastrada com sucesso.'),
    'campo': _(u'Campo'),
    'cancelar': _(u'Cancelar'),
    'cancelada': _(u'Cancelada'),
    'canceladas': _(u'Canceladas'),
    'candidatar': _(u'Candidatar'),
    'candidatar_ja_candidatado': _(u'Você já se candidatou para esta vaga.'),
    'candidatar_no_proc_sel': _(u'Você já participa do processo seletivo desta vaga.'),
    'candidatar_termo_alerta': _(u'Para efetuar o cadastro e utilizar os serviços deste portal o usuário deve estar de acordo com o termo de responsabilidade ativando o campo \'Eu li e aceitei os termos e condições.\''),
    'candidatar_fotos_obrigatorias': _(u'Para efetuar o cadastro e utilizar os serviços deste portal o usuário deve preencher todas as fotos na aba Fotos em seu Currículo.'),
    'candidatar_sucesso': _(u'A sua candidatura à vaga de {} foi registrada com sucesso!'),
    'candidato': _(u'Candidato'),
    'candidatos': _(u'Candidatos'),
    'candidato_ativo': _(u'Candidato Ativo'),
    'cadastro_compromisso': _(u'Cadastro de Compromisso'),
    'cadastro_compromisso_log': _(u'''
        O U
    '''),
    'cadastro_evento': _(u'Cadastro de Evento'),
    'candidato_inativo': _(u'Candidato Inativo'),
    'candidato_inativo_ate': _(u'Candidato Inativo até'),
    'candidato_nao_encontrado': _(u'O Candidato não foi encontrado.'),
    'candidato_restrito': _(u'Candidato com Restrição'),
    'candidato_sucesso': _(u"O candidato foi salvo com sucesso."),
    'candidato_visto': _(u"Candidato visualizado."),
    'candidatos_aprovados': _(u'Candidatos Aprovados'),
    'candidatos_com_processo_seletivo': _(u'Candidatos com Processo Seletivo'),
    'candidatos_encaminhados': _(u'Candidatos Encaminhados'),
    'candidatos_importados_achaempregos': _(u'Candidatos Importados do Achaempregos'),
    'candidatos_importados_bne': _(u'Candidatos Importados do BNE'),
    'candidatos_importados_sucesso': _(u'Candidato Importado com Sucesso'),
    'candidatos_importados_novo_codigo': _(u'O Código do Novo Candidato é {}.'),
    'candidatos_ativos': _(u'Candidatos Ativos'),
    'candidatos_encontrados': _(u'Candidatos Encontrados'),
    'candidatos_inativos': _(u'Candidatos Inativos'),
    'candidatos_homonimos_encontrados': _(u'Candidatos Homônimos Encontrados'),
    'candidatos_restritos': _(u'Candidatos Restritos'),
    'candidatos_restritos_consulta_descricao': _(u'Consulta quais são os Candidatos com Restrições cadastradas para os Clientes.'),
    'candidatos_faturados': _(u'Candidatos Faturados'),
    'candidatos_n_faturados': _(u'Candidatos Não Faturados'),
    'candidatos_com_deficiencia': _(u'Com Deficiência'),
    'candidatos_sem_assinatura_premium': _(u'Sem Assinatura Premium'),
    'candidatura': _(u'Candidatura'),
    'candidaturas': _(u'Candidaturas'),
    'candidatura_desativada': _(u'Candidatura Desativada'),
    'candidatar_se_a_vaga': _(u'Candidatar-se à Vaga'),
    'candidatura_nao_encontrada': _(u'Candidatura não encontrada.'),
    'cand_aprovado_folha': _(u'Candidatos Aprovados para Folha'),
    'cand_aprovado_folha_descricao': _(u'Consulte e exporte os Candidatos Aprovados para Folha.'),
    'cand_aprovado_folha_log': _(u'O usuário executou uma exportação de candidatos com os seguintes códigos: {}'),
    'cand_aprovado_folha_val_cands': _(u'Selecione pelo menos um candidato para realizar a exportação.'),
    'cand_anexo_sucesso': _(u'O Anexo do Candidato foi salvo com sucesso.'),
    'cand_conceito': _(u'Conceito de Candidato'),
    'cand_conceitos': _(u'Conceitos de Candidato'),
    'cand_doc_pessoais': _(u'Documentos Pessoais'),
    'cand_idioma': _(u"Idioma do Candidato"),
    'cand_idiomas': _(u"Idiomas do Candidato"),
    'cand_filho': _(u'Filho do Candidato'),
    'cand_filhos': _(u'Filhos do Candidato'),
    'cand_foto': _(u'Foto do Candidato'),
    'cand_fotos': _(u'Fotos do Candidato'),
    'cand_origem': _(u'Origem de Candidato'),
    'cand_origens': _(u'Origens de Candidato'),
    'cand_outras_infor': _(u'Outras Informações'),
    'cand_tipo': _(u'Tipo de Candidato'),
    'cand_tipos': _(u'Tipos de Candidato'),
    'campos_cadastros': _(u'Campos dos Cadastros'),
    'campos_disp_obr_cand': ('Campos Disponíveis e Obrigatórios do Cadastro de Candidato'),
    'campos_disp_obr_cli': ('Campos Disponíveis e Obrigatórios do Cadastro de Cliente'),
    'campos_disp_obr_vaga': ('Campos Disponíveis e Obrigatórios do Cadastro de Perfil da Vaga'),
    'campos_especificacao_vaga_portal': _(u'Campos Visualizados na Especificação da Vaga'),
    'campos_obrigatorios': _(u'Campos Obrigatórios'),
    'campos_obrigatorios_preenchidos': _(u"Campo Obrigatórios não preenchidos"),
    'campos_obrigatorios_instrucao' :_(u"Os campos com asterisco vermelho são obrigatórios"),

    'campos_para_selecao': _(u'Campos para Seleção'),
    'campos_selecionados': _(u'Campos Selecionados'),
    'casa_propria': _(u'Casa Própria?'),
    'caracteristicas_pessoais': _(u'Características Pessoais'),
    'carga_horaria': _(u'Carga Horária"'),
    'carregar_mais': _(u'Carregar Mais'),
    'cartao': _(u'Cartão'),
    'cart_profis': _(u'Carteira de Trabalho'),
    'carteira_estrangeiro': _(u'Carteira de Estrangeiro'),
    'categoriacnh': _(u'Categoria da CNH'),
    'catho_url': _(u'Url da API'),
    'catho_app_token': _(u'APP Token'),
    'catho_auth_token': _(u'Auth Token'),
    'catho_publicada': _(u"Vaga Publicada na Catho"),
    'catho_publicada_descricao': _(u'Vaga Publicada em {}  pelo usuário {}. <br/>Código da Vaga na Catho: {}<br/>Status: <b>{}</b>'),
    'catho_publicacao_instrucao': _(u"Cliquei em 'Publicar' para publicar a vaga na Catho"),
    'catho_publicacao_obrigatorios_instrucao': _(u"Para realizar a publicação da vaga na Catho, é necessário que, os seguintes campos estejam corretamente preenchidos:"),
    'catho_publicacao_sucesso': _(u"Vaga publicada com sucesso."),
    'catho_publicacao_sem_recrutador': _(u'É necessário pelo menos um recrutador cadastrado no Parâmetros do Sistema'),
    'catho_publicacao_cad_vaga_atualizado': _(u"Cadastro de Vaga: A vaga foi atualizada na Catho."),
    'catho_publicacao_cad_vaga_publicada': _(u"Cadastro de Vaga: A vaga foi publicada na Catho."),
    'catho_desativada_sucesso': _(u"Vaga desativada com sucesso."),
    'catho_reativada_sucesso': _(u"Vaga reativada com sucesso."),
    'catho_erro_interno': _(u'Erro Interno na integração com a Catho'),
    'catho_erro_manutencao': _(u'Integração com a Catho em Manutenção'),
    'catho_tratar_indisponibilidade_log': _(u'Cadastro de Vaga: Vaga não esta mais disponivel para Internet.'),
    'catho_mudanca_status_log': _(u"Manutenção da vaga: alteração de status para {}, vaga foi desativada."),
    'catho_atualizacao_log':_(u"Cadastro da Vaga: Atualização de informações da vaga.  A vaga foi atualizada na Catho."),
    'casado_brasileiro': _(u'Casado(a) com Brasileiro(a)'),

    'cei': _(u'C.E.I.'),
    'celular': _(u'Celular'),
    'celular_n_cadastrado': _(u'Candidato sem celular informado.'),
    'cep': _(u'CEP'),
    'cep_cobr': _(u'CEP Cobr.'),
    'cep_invalido': _(u'CEP inválido.'),
    'cep_n_encontrado': _(u'CEP não encontrado.'),
    'cep_pesquisando': _(u'Pesquisando CEP.'),

    'changelog_title': _(u"Changelog"),
    'changelog_description': _(u"Detalhamento dos itens que foram desenvolvidos em cada versão do SPA"),
    'changelog_nova_implementacao': _(u"Novas Implementações"),
    'changelog_bugs': _(u"Correção Específicas"),

    'cid1': _(u"C.I.D.1"),
    'cid2': _(u"C.I.D.2"),
    'cidade': _(u'Cidade'),
    'cidade_cobr': _(u'Cidade Cobr.'),
    'cidade_estado': _(u'Cidade - Estado'),
    'cidade_pesquisando': _(u'Pesquisando Cidades'),
    'cidade_filtro': _(u'Filtre uma ou mais cidades'),
    'cidade_filtro_all': _(u'Filtrar todas as cidades / Nenhuma'),
    'cidade_n_informada': _(u'Cidade não informada'),
    'cidade_trabalho': _(u'Cidade de Trabalho'),
    'cidade_rg': _(u'Cidade (RG)'),
    'cidade_nascimento': _(u'Cidade de Nascimento'),

    'cliente': _(u'Cliente'),
    'clientes': _(u'Clientes'),
    'cliente_perfil': _(u'Perfil do Cliente'),
    'cliente_nao_encontrado': _(u'O Cliente não foi encontrado.'),
    'cliente_produz': _(u'O que produz'),
    'clientexpromotor': _(u'Cliente x Promotor'),
    'clique_aqui': _(u'Clique Aqui'),
    'clique_cadastrar': _(u'Clique para Cadastrar'),
    'clique_abrir_menu': (u'Clique para Abrir o Menu'),
    'clique_para_dicas': (u'Clique para Dicas'),
    'clique_para_download': (u'Clique para efetuar o Download.'),
    'clique_para_acessar': _(u'Clique para Acessar'),
    'clique_para_pesquisar': _(u'Clique para Pesquisar'),
    'cli_beneficio': _(u'Benefício do Cliente'),
    'cli_beneficios': _(u'Benefícios do Cliente'),
    'cli_porte': _(u'Porte do Cliente'),
    'cli_portes': _(u'Portes do Cliente'),
    'cli_produto': _(u'Produto que o Cliente Consome'),
    'cli_produtos': _(u'Produtos que o Cliente Consome'),
    'cli_promotor': _('Promotor do Cliente'),
    'cli_promotores': _('Promotores do Cliente'),
    'cli_proposta': _(u'Proposta do Cliente'),
    'cli_propostas': _(u'Propostas do Cliente'),
    'cli_servico': _(u'Serviço do Cliente'),
    'cli_servicos': _(u'Serviços do Cliente'),
    'cli_taxa': _(u'Taxa do Cliente'),
    'cli_taxas': _(u'Taxas do Cliente'),
    'cli_taxa_vaga': _(u'Taxa da Vaga'),
    'cli_tipo': _(u'Tipo de Cliente'),
    'cli_tipos': _(u'Tipos de Cliente'),
    'cli_contato_aberto' : _(u'Clientes com Contatos em Abertos'),
    'cli_controle_acesso': _(u'Controle de Acesso do Cliente'),

    'cnpj': _(u'CNPJ'),
    'cnpj_cpf': _(u'CNPJ/ CPF'),
    'cnpj_cli_duplic': _(u'Permitir CNPJ duplicado no Cadastro de Cliente'),
    'cnpj_duplicado_cli': _(u'Já existe um Cliente com este CNPJ.'),
    'cnpj_cobranca_duplicado_cli' : _(u'Já existe um Cliente com este CNPJ de Cobrança.'),

    'cod': _(u'Cód.'),
    'cod_vaga': _(u'Cód. da Vaga'),
    'codigo': _(u'Código'),
    'codigo_bne': _(u'Código BNE'),
    'codigo_contrato': _(u'Código Contrato'),
    'codigo_etalent': _(u'Código Etalent'),
    'codigo_financeiro': _(u'Código Financeiro'),
    'codigo_folha': _(u'Código da Folha de Pagamento'),
    'codigo_folha_cliente': _(u'Código da Folha'),
    'codigo_vaga': _(u'Código da Vaga'),
    'codigo_nome': _(u'Código ou Nome'),
    'codigo_outros_sistemas': _(u'Código de Outros Sistemas'),
    'codigo_spa': _(u'Código do SPA'),
    'codigo_xml_vagas': _(u'XML - Vagas Abertas - Código de Segurança'),
    'codigo_xml_vagas_help_text': _(u''' Utilize o código abaixo para gerar o xml com as vagas
                abertas. Clique em "Gerar Novo" para trocar o código. '''),
    'colaborador': _(u'Colaborador'),
    'colaboradores': _(u'Colaboradores'),
    'colocar_extensao_arquivo': _(u'Colocar a extensão do arquivo.'),
    'codigo_proposta': _(u'Código da Proposta'),
    'codigo_integracao_outros': _(u'Códigos de Integração com Outros Sistemas - Campos Informativos '),
    'compareceu': _(u'Compareceu'),
    'compareceu_em': _(u'Compareceu em'),
    'comparecimento': _(u'Comparecimento'),
    'comparecimento_detalhes_title': _(u'Convocação do Candidato'),
    'comparecimento_inserir_title': _(u'Convocar Candidato'),
    'comparecimento_sucesso': _(u'Candidato convocado com sucesso.'),
    'comparecimento_remover_confirma' : _(u'Deseja realmente remover o Comparecimento?'),
    'comparecimento_remover_sucesso' : _(u'O Comparecimento foi removido com sucesso.'),
    'comparecimento_consulta_descricao' : _(u'Consulte e Gerencie os Comparecimentos dos Candidatos.'),
    'comparecimento_ja_adicionado': _(u'O Candidato já esta convocado.'),
    'comparecimento_nao_encontrado': _(u'O Comparecimento não foi encontrado.'),
    'comparecimentos': _(u'Comparecimentos'),
    'compartilhar_facebook': _(u'Compartilhar via Facebook'),
    'compartilhar_twitter': _(u'Compartilhar via Twitter'),
    'compartilhar_linkedin': _(u'Compartilhar via Linkedin'),
    'compartilhar_catho': _(u'Compartilhar via Catho'),
    'compartilhar_parceiros': _(u'Compartilhar via Parceiros'),
    'compartilhar_infojobs':  _(u'Compartilhar via Infojobs'),
    'compartilhar_erro_vaga_disponivel': _(u'Para realizar a publicação da vaga, é necessário que a vaga esteja Disponível para Internet.'),
    'compartilhar_erro_vaga_fechada': _(u'Para realizar a publicação da vaga, é necessário que a vaga esteja Aberta ou Reaberta.'),
    'compartilhar_erro_vaga_confidencial': _(u'Para realizar a publicação da vaga, é necessário que a vaga não seja confidencial.'),
    'compromisso': _(u'Compromisso'),
    'compromisso_carregar': _(u'Houve um erro ao carregar os compromissos'),
    'compromisso_choque_hora': _(u'Já existe um compromisso agendado neste horário para um dos usuários selecionados. Selecione um novo horário.'),
    'compromisso_data_retroativa': _(u'Não pode criar novos compromissos em datas anteriores a de hoje.'),
    'compromisso_excluir_confirmar': _(u'Deseja realmente excluir esse Compromisso?'),
    'compromisso_excluir_sucesso': _(u'O Compromisso foi excluído com sucesso.'),
    'compromisso_excluir_erro': _(u'Ocorreu um erro ao excluir o Compromisso.'),
    'compromisso_erro_aniversario': _(u'Não é possivel criar Compromisso de "Lembrete de Aniversário", ele é gerado automaticamente.'),
    'compromisso_erro_aniversario_alterar_data': _(u'Não é possivel mudar data e hora de um Compromisso de "Lembrete de Aniversário", ele é gerado automaticamente.'),
    'compromisso_intervalo_invalido': _(u'Apenas é possivel salvar compromissos com data e hora de inicio após a atual.'),
    'compromisso_log_alterar_data': _(u"""
        O Usuário alterou a Data/ Hora do Compromisso:<br>
            ({codigo}) {assunto}.<br/>
        {data_antiga}: <br>
            - de {inicio_antigo} até {fim_antigo} <br/>
        {data_atual}: <br>
            - de {inicio} até {fim}
    """),
    'compromisso_alterar_data_sucesso': _('Data/ Hora do Compromisso alteradas com sucesso'),
    'compromisso_prioritario': _(u'Compromisso Prioritário'),
    'compromisso_n_encontrado': _(u'Compromisso não encontrado.'),
    'compromisso_salvo': _(u'Compromisso salvo com sucesso.'),
    'compromisso_sem_usuario': _(u'Compromisso salvo com sucesso.'),
    'compromisso_retroativo': _(u'Compromisso Retroativo'),
    'compromisso_retroativo_alterar_data': _(u'Não é possivel mudar o Compromisso para data anteriores a atual.'),
    'compromisso_usuario_obrigatorio': _(u'É necessário pelo menos um Usuário para salvar o Compromisso.'),
    'compromissos': _(u'Compromissos'),
    'compromissos_do_dia': _(u'Compromissos do Dia'),
    'compromissos_padrao': _(u'Compromissos Padrões'),
    'complemento': _(u'Complemento'),
    'complemento_cobr': _(u'Complemento Cobr.'),
    'completo': _(u'Completo'),
    'comentario': _(u"Comentário"),
    'comercial': _(u'Comercial'),
    'comercial_produto': _(u'Comercial - Produto'),
    'conceito': _(u'Conceito'),
    'conceito_cand': _(u'Conceito do Candidato'),
    'conceito_cand_alteracao': _(u"Alteração de Conceito de Candidato"),
    'conceito_cand_duplicado_desc': _(u'Já existe um Conceito de Candidato com essa descrição.'),
    'conceito_cand_duplicado_sigla': _(u'Já existe um Conceito de Candidato com essa sigla.'),
    'conceito_cand_sucesso': _(u"O Conceito de Candidato foi salvo com sucesso."),
    'conceito_cand_nao_encontrado': _(u'O Conceito de Candidato não foi encontrado.'),
    'conducao_local': _(u'Condução Local'),
    'consulta': _(u'Consulta'),
    'condicao': _(u'Condição'),
    'confidencial': _(u'Confidencial'),
    'confirmar': _(u'Confirmação'),
    'confirmar_senha': _(u'Confirmar Senha'),
    'configuracao': _(u'Configuração'),
    'configuracoes': _(u'Configurações'),
    'configuracao_cores': _(u'Configuração de Cores - Vagas em Aberto'),
    'configuracao_termos_assinados': _(u'Configuração de Termos de Assinatura'),
    'configure_campos_cadastros': _(u'Configure quais são os campos disponíveis e obrigatórios dos Cadastros de Candidato, Cliente e Perfil da Vaga.'),
    'configuracao_gerais': _(u"Configurações Gerais"),
    'config_bne': _(u'Configuração da Busca de Currículos pelo BNE'),
    'config_bne_habilitar': _(u'Habilitar a Busca de Currículos pelo BNE'),
    'config_bne_n_habilitada': _(u'A seleção de currículos pelo BNE não está habilitada. Favor ir em Parâmetros do Sistema para habilitar.'),
    'config_bne_invalida': _(u'A seleção de currículos pelo BNE não está configurada. Favor ir em Parâmetros do Sistema para configurar.'),
    'config_bne_indisponivel': _(u'A seleção de currículos pelo BNE esta indisponível. Favor verifique as configurações no Parâmetros do Sistema.'),
    'config_catho': _(u'Configuração Integração Catho'),
    'config_campos_cadastros': _(u'Configuração dos Campos dos Cadastros'),
    'config_campos_cadastros_salvos': _(u'Os Campos dos Cadastros foram salvos com sucesso.'),
    'config_campos_cadastros_alteracao': _(u"Alteração de Campos dos Cadastros"),
    'config_multiportais': _(u'Configuração Múltiplos Portais do Candidato'),
    'config_multiportais_help': _(u'Cadastre os layouts dos portais que você deseja ter no SPA.'),
    'convivencia_cand_duplicadas': _(u'Já existe um integrante com este CPF vinculado ao seu cadastro.'),
    'convivencia_n_preenchidas': _(u'Existem integrantes não preenchidos. Para adicionar outros, preencha primeiro os adicionados.'),
    'conta': _(u'Conta'),
    'conta_corrente': _(u'Conta Corrente'),
    'contato': _(u'Contato'),
    'contato_cliente': _(u'Contato do Cliente'),
    'contatos_cliente': _(u'Contatos do Cliente'),
    'contato_sem_email': _(u'Contato sem e-mail.'),
    'contato_sem_login': _(u'O Contato está sem login. É preciso um login para efetuar acesos ao Portal.'),
    'continuar_lendo': _(u'Continuar lendo'),
    'controlar_acesso_promotores_confirmar_desabilitar': _(u'Deseja realmente deixar desativado o Controle de Acesso de Promotores? Ao desativar, todas as configurações de permissões feitas por promotores serão apagadas e não poderá ser desfeito.'),
    'controlar_acesso_promotores_habilitar': _(u'Habilitar o Controle de Acesso de Promotores'),
    'controlar_acesso_promotores_habilitar_instrucao': _(u'Ao habilitar esta opção, a edição do Cliente terá Controle de Acesso. Apenas os promotores e os Administradores poderão acessar a edição de seus clientes.'),
    #'controlar_acesso_promotores_habilitar_instrucao': _(u'Ao habilitar esta opção, a edição do Cliente terá Controle de Acesso. O promotor e os Administradores poderão acessar sem permissões a edição e escolher quais usuários e quais processos ficarão permitidos para eles.'),
    'controlar_acesso_usuario_habilitar': _(u'Controlar de Acesso de outros Usuarios à edição do seu Cliente.'),
    'controlar_acesso_usuario_habilitar_instrucao': _(u'Ao habilitar esta opção, a edição do seu Cliente terá Controle de Acesso, apenas você (Promotor) e os adminstradores poderão acessar sem permissões e você poderá controlar quais usuários e quais processos ficarão permitidos para eles.'),
    'controlar_acesso_sem_abas': _(u'Você não tem acesso aos Processos da Edição do Cliente. Entre em contato com o Administrador do sistema'),
    'cor_aviso': _(u'Cor do Aviso'),

    'chave_sistema': _(u'Chave do Sistema'),
    'chave_api': _(u'Chave da API'),

    'cpf': _(u'CPF'),
    'cpf_usuario': _(u'CPF do Usuário'),
    'cpf_encontrado': _(u'CPF encontrado'),
    'cpf_n_encontrado': _(u'CPF não encontrado'),
    'cpf_duplicado_cand': _(u'Este CPF já esta cadastrado.'),
    'cpf_duplicado_cand_confirm': _(u'Foi encontrado um candidato com o mesmo CPF. Deseja abrir o cadastro do candidato encontrado?'),
    'cpf_conjuge': _(u'CPF do Cônjuge.'),

    'cnpj': _(u'CNPJ'),
    'cnpj_cpf': _(u'CNPJ/ CPF'),
    'cnpj_cobr': _(u'CNPJ Cobr.'),
    'cnpj_empresa': _(u'CNPJ da Empresa'),

    'colaboradores': _(u'Colaboradores'),
    'comparecimento': _(u'Comparecimento'),
    'config_cvpadrao_auto': _(u'Gerar CV Padrão automaticamente'),
    'config_cvpadrao_manual': _(u'Abrir tela de seleção dos campos para geração do CV padrão'),
    'config_cvpadrao': _(u'Configuração do CV Padrão'),
    'config_cvpadrao_salvar': _(u'Salvar configurações do CV Padrão'),
    'config_cvpadrao_salvando': _(u'Salvando configurações...'),
    'config_cvpadrao_gerar': _(u'Gerar CV Padrão'),
    'config_cvpadrao_gerando': _(u'Gerando CV Padrão, aguarde...'),
    'config_colunas': _(u'Configurar Colunas'),
    'config_colunas_obrigatorio': _(u'É necessário pelo menos uma coluna selecionada para salvar a configuração.'),
    'config_colunas_sucesso': _(u'A configuração de colunas foi salva com sucesso.'),
    'config_ead': _(u'Configuração do EAD'),
    'config_favoritos': _(u'Configuração dos Favoritos'),
    'config_fila_selecao': _(u'Configuração da Fila de Seleção'),
    'config_infojobs': _(u'Configuração Integração Infojobs'),
    'config_infojobs_help': _(u'Insira abaixo as informações de conexão com a Infojobs'),
    'configurar_colunas_listagem': _(u'Clique para Configurar as Colunas da Listagem'),
    'configurar_colunas_texto': _(u'''Clique e arraste os campos desejados para selecionar ou remover do Layout da Listagem.
    Tem que haver ao menos uma coluna selecionada em Campos Selecionados.
    Se retiradas todas e solicitado o salvamento fará com que todas as colunas sejam inseridas.'''),
    'config_sms': _(u'Configuração de SMS'),
    'config_sms_titulo': _(u'Configure o Fornecedor de SMS utilizado pela sua empresa.<br/>Para alguns fornecedores será necessário informar o login e a senha de conexão para o envio de sms.'),
    'config_sms_banners': _(u'Adicione abaixo os banners para a tela do PagSeguro.<br/>Ao inserir os banners clique no botão Salvar para realizar a alteração.'),
    'conjuge': _(u'Nome do Cônjuge'),
    'conhec_habilidades': _(u'Conhec./ Habilidades'),
    'conhecimentos_habilidades': _(u'Conhecimentos/Habilidades'),
    'conhecimentos_habilidades_candidato': _(u'Conhecimentos/Habilidades do Candidato'),
    'conhecimentos_habilidades_vaga': _(u'Conhecimentos/Habilidades da Vaga'),
    'conhec_hab_cand_duplicado': _(u"Já existe um Conhecimento/Habilidade com esses dados para o candidato."),
    'conhec_hab_cand_nao_encontrado': _(u'O Conhecimento/Habilidade do Candidato não foi encontrado.'),
    'conhec_hab_cand_sucesso': _(u'O Conhecimento/Habilidade do Candidato foi salvo com sucesso.'),
    'conhec_hab_vaga_duplicado': _(u"Já existe um Conhecimento/Habilidade com esses dados para a vaga."),
    'conhec_hab_vaga_nao_encontrado': _(u'O Conhecimento/Habilidade da Vaga não foi encontrado.'),
    'conhec_hab_vaga_sucesso': _(u'O Conhecimento/Habilidade da Vaga foi salvo com sucesso.'),
    'consultar': _(u'Consultar'),
    'consulta': _(u'Consulta'),
    'consultas': _(u'Consultas'),
    'consulta_permissao_abas': _(u'Consulta de Permissões das Abas'),
    'consulta_permissao_telas': _(u'Consulta de Permissões das Telas'),
    'consumido': _(u'Consumido'),
    'consumo_candidato_mil': _(u'Consumo de Candidato (em MIL)'),
    'consumo_storage_mb': _(u'Consumo de Storage (em MB)'),
    'contato': _(u'Contato'),
    'contatos': _(u'Contatos'),
    'contatos_cliente': _(u'Contatos no Cliente'),
    'contato_cliente_nao_encontrado': _(u'O Contato de Cliente não foi encontrado.'),
    'contato_cliente_sucesso': _(u'O Contato de Cliente foi salvo com sucesso.'),
    'contratado': _(u'Contratado'),
    'controle_acesso': _(u'Controle de Acesso'),
    'controle_ip': _(u'Controle de Acesso por IP'),
    'controle_ip_ativar': _(u'Deseja utilizar o Controle de Acesso por IP?'),
    'controle_ip_sucesso': _(u'IP salvo com sucesso.'),
    'controle_ip_desabilita_alerta': _(u'Deseja realmente desabilitar o Controle de Acesso por IP? Os IPs cadastrados serão excluídos.'),
    'controle_ip_sucesso_desabilita': _(u'Controle de Acesso por IP desabilitado com sucesso. Os IPs cadastrados foram excluídos.'),
    'controle_ip_sucesso_remocao' : _(u'IP removido com sucesso.'),
    'controle_ip_sucesso_remocao_ips' : _(u'IP removido com sucesso. O Controle de Acesso por IP foi desabilitado por não conter mais nenhum IP cadastro.'),
    'controle_usuario': _(u'Controle de Usuário'),
    'convocar': _(u'Convocar'),

    'copiar': _(u'Copiar'),
    'copia_vaga': _(u'Cópia da Vaga'),
    'copia_vaga_descricao': _(u'Realize cópia do Perfil das Vagas desejadas. Ao copiar uma vaga será gerado um novo perfil de vaga com base no já escolhido.'),
    'copia_vaga_cliente_alerta': _(u'Ao trocar o Cliente da vaga, alguns campos como os de endereço, taxas, filiais e benefícios serão alterados.'),
    'copia_vaga_participantes': _(u'Copiar Participantes do Processo Seletivo'),
    'copia_vaga_fila_candidatura': _(u'Copiar Fila de Candidatura'),
    'copia_vaga_inativos': _(u'Copiar Candidatos Inativos'),
    'copia_vaga_testes': _(u'Copiar Teste Online'),
    'copia_vaga_vaga_obr': _(u'A Vaga de Origem é obrigatória para realizar o processo de cópia.'),
    'copia_vaga_sucesso': _(u"""
       A Vaga foi copiada com sucesso. <a href="{}">Acesse aqui</a>
       para visualizar o cadastro.
    """),
    'copia_vaga_log': _(u'''Realizada Cópia da Vaga de {} para {}.'''),

    'cor_verde': _(u'Verde'),
    'cor_verde_claro': _(u'Verde Claro'),
    'cor_amarelo': _(u'Amarelo'),
    'cor_laranja': _(u'Laranja'),
    'cor_roxo': _(u'Roxo'),
    'cor_azul': _(u'Azul Claro'),
    'cor_vermelho': _(u'Vermelho'),
    'cor_cinza': _(u'Cinza'),
    'cor_dias_abertura_vaga': _(u'Cor dos Dias de Abertura da Vaga'),
    'corporativo': _(u'Corporativo'),

    'cracha':_(u'Crachá'),
    'credito_sms': _(u'Crédito de SMS'),
    'criacao': _(u"Criação"),
    'criar_senha': _(u'Criar Senha'),

    'curso': _(u'Curso'),
    'curriculo': _(u'Currículo'),
    'curriculo_candidato': _(u'Currículo do Candidato'),
    'curriculo_inexistente': _(u'Currículo inexistente.'),
    'curriculo_sem': _(u'O Candidato não tem currículo anexo.'),
    'curriculo_erro_formato': _(u'Currículo em formato não permitido. Os arquivos aceitos são: %s.'),
    'curriculo_erro_formato_simples': _(u'Currículo em formato não permitido.'),
    'curriculo_removido': _(u'Currículo removido com sucesso.'),

    'cv': _(u'CV'),
    'cvpadrao': _(u'CV Padrão'),
    'cv_padrao_sem_candidatos': _(u"Não foram encontrados candidatos para geração do CV Padrão."),

}
