from django.utils.translation import ugettext as _

textos_d = {
    'dados_basicos': _(u'Dados Básicos'),
    'dados_cadastrais': _(u'Dados Cadastrais'),
    'dados_candidato': _(u'Dados do Candidato'),
    'dados_contato': _(u'Dados para Contato'),
    'dados_cobranca': _(u'Dados para Cobrança'),
    'dados_endereco': _(u'Dados de Endereço'),
    'dados_estrangeiro': _(u'Dados de Estrangeiro'),
    'dados_gerais': _(u'Dados Gerais'),
    'dados_pessoais': _(u'Dados Pessoais'),
    'dados_principais': _(u'Dados Principais'),
    'dados_profissionais': _(u'Dados Profissionais'),
    'dados_solicitante': _(u'Dados do Solicitante'),
    'dados_vaga': _(u'Dados da Vaga'),
    'dashboard': _(u'Dashboard'),
    'data': _(u'Data'),
    'datas': _(u'Datas'),
    'data_abertura': _(u'Data de Abertura'),
    'data_abertura_ini': _(u"Data Abertura Inicial"),
    'data_abertura_fin': _(u"Data Abertura Final"),
    'data_aceite': _(u'Data do Aceite'),
    'data_admissao': _(u"Data de Admissão"),
    'data_alteracao': _(u'Data de Alteração'),
    'data_antiga': _(u'Data Antiga'),
    'data_aprovacao': _(u"Data Aprovação"),
    'data_aprovacao_processo': _(u"Data Aprovação no Processo Seletivo"),
    'data_aprovacao_ini': _(u"Data Aprovação Inicial"),
    'data_aprovacao_fin': _(u"Data Aprovação Final"),
    'data_atual': _(u'Data Atual'),
    'data_atualizacao': _(u'Data de Atualização'),
    'data_atualizacao_ini': _(u'Data de Atualização Inicial'),
    'data_atualizacao_fin': _(u'Data de Atualização Final'),
    'data_bloqueio': _(u'Data de Bloqueio'),
    'data_candidatura': _(u'Data de Candidatura'),
    'data_cadastro': _(u"Data de Cadastro"),
    'data_cadastro_ini': _(u"Data de Cadastro Inicial"),
    'data_cadastro_fin': _(u"Data de Cadastro Final"),
    'data_cipa': _(u'Data da CIPA'),
    'data_comparecimento': _(u'Data do Comparecimento'),
    'data_conclusao': _(u"Data de Conclusão"),
    'data_contrato': _(u"Data de Contrato"),
    'data_contrato_ini': _(u"Data de Contrato Inicial"),
    'data_contrato_fin': _(u"Data de Contrato Final"),
    'data_demissao': _(u"Data de Demissão"),
    'data_emissao': _(u"Data de Emissão"),
    'data_emissao_ct': _(u"Data de Emissão (CT)"),
    'data_emissao_ini': _(u"Data de Emissão Inicial"),
    'data_emissao_fin': _(u"Data de Emissão Final"),
    'data_emissao_rg': _(u"Data de Emissão do RG"),
    'data_emissao_titulo': _(u"Data de Expedição do Título Eleitor"),
    'data_encaminhamento': _(u'Data de Encaminhamento'),
    'data_encerramento': _(u"Data de Encerramento"),
    'data_encerramento_ini': _(u"Data de Encerramento Inicial"),
    'data_encerramento_fin': _(u"Data de Encerramento Final"),
    'data_encerramento_proposta': _(u"Informe a data de encerramento da proposta"),
    'data_entrada': _(u"Data de Entrada"),
    'data_entrada_ini': _(u"Data de Entrada Inicial"),
    'data_entrada_pais': _(u"Data de Entrada no País"),
    'data_etapa': _(u"Data da Etapa"),
    'data_etapa_processo': _(u"Data da Etapa do Processo Seletivo"),
    'data_expiracao': _(u'Data de Expiração'),
    'data_e_hora_inicial': _(u'Data e Hora Inicial'),
    'data_e_hora_final': _(u'Data e Hora Final'),
    'data_fin': _(u"Data Final"),
    'data_fase': _(u"Data da Fase"),
    'data_fechamento': _(u"Data de Fechamento"),
    'data_hora': _(u'Data/ Hora'),
    'data_hora_login': _(u'Data e Hora Login'),
    'data_hora_logout': _(u'Data e Hora Logout'),
    'data_insercao_processo': _(u"Data de Inserção no Processo Seletivo"),
    'data_inativacao': _(u"Data de Inativação"),
    'data_ini': _(u"Data Inicial"),
    'data_inicio': _(u"Data de Inicio"),
    'data_inicio_processo': _(u"Data de Inicio do Trabalho"),
    'data_insercao': _(u"Data de Inserção"),
    'data_limite_contrato': _(u"Data do Limite do Contrato"),
    'data_limite_teste': _(u"Data do Limite do Teste Online"),
    'data_login': _(u"Data/ Hora de Login"),
    'data_login_ini': _(u"Data de Login Inicial"),
    'data_login_fin': _(u"Data de Login Final"),
    'data_logout': _(u"Data/ Hora de Logout"),
    'data_logout_ini': _(u"Data de Logout Inicial"),
    'data_logout_fin': _(u"Data de Logout Final"),
    'data_nascimento': _(u"Data de Nascimento"),
    'data_naturalizacao': _(u"Data de Naturalização"),
    'data_ocorrencia': _(u"Data da Ocorrência"),
    'data_ocorrencia_ini': _(u"Data da Ocorrência Inicial"),
    'data_ocorrencia_fin': _(u"Data da Ocorrência Final"),
    'data_pagamento': _(u'Data do Pagamento'),
    'data_parecer': _(u'Data do Parecer'),
    'data_premium_inicio': _(u'Data Início de Assinatura'),
    'data_premium_fim': _(u'Data Expiração de Assinatura'),
    'data_prevista': _(u'Data Prevista'),
    'data_publicacao': _(u'Data de Publicação'),
    'data_realizada': _(u'Data Realizada'),
    'data_reativacao_ini': _(u"Data de Reativação Inicial"),
    'data_reativacao_fin': _(u"Data de Reativação Final"),
    'data_restricao': _(u"Data da Restrição"),
    'data_restricao_ini': _(u"Data da Restrição Inicial"),
    'data_restricao_fin': _(u"Data da Restrição Final"),
    'data_requisicao': _(u"Data de Requisição"),
    'data_requisicao_ini': _(u"Data de Requisição Inicial"),
    'data_requisicao_fin': _(u"Data de Requisição Final"),
    'data_retroativa': _(u'A Data não pode ser retroativa.'),
    'data_hora_retroativa': _(u'A Data e Hora não podem ser retroativas.'),
    'data_intervalo_invalido': _(u'A Data e Hora Inicial devem ser menores que a Data e Hora Final.'),

    'ddd': _(u'DDD'),
    'ddd_celular': _(u'DDD Celular'),
    'dddcel_invalido': _(u'DDD Celular inválido, informe somente números, 99.'),

    'de_invalido': _('O campo De inválido.'),
    'deficiencia': _(u'Deficiência'),
    'deficiencias': _(u'Deficiências'),
    'deficiencias_aceitas': _(u'Deficiências Aceitas'),
    'deficiencia_aceita_portadores':_(u'Deficiência Aceita Portadores de Deficiências'),
    'deficiencia_duplicada':_(u"Já existe uma Deficiência com essa descrição."),
    'deficiencia_nao_encontrada': _(u'A Deficiência não foi encontrada.'),
    'deficiencia_sucesso': _(u"A Deficiência foi salva com sucesso."),
    'default_candidato_sistema': _(u'Default do Candidato (Cadastro pelo Sistema)'),
    'default_candidato_portal': _(u'Default do Candidato (Cadastro pelo Portal)'),
    'default_cliente': _(u'Default do Cliente'),
    'default_vaga': _(u'Default da Vaga'),
    'default_documentos_impressao': _(u'Default do Documento para Impressão'),
    'departamento_atuacao': _(u'Departamento de Atuação'),
    'desativada': _(u'Desativada'),
    'desativar': _(u'Desativar'),
    'desativacao_vaga': _(u"Desativação da vaga"),
    'descartar_aviso': _(u'Descartar Aviso'),
    'descartar_aviso_instrucao': _(u'Tem certeza de que deseja descartar as Notificações para esse Compromisso?'),
    'descartar_aviso_sucesso': _(u'Notificações descartadas. Você não receberá novas Notificações deste Compromisso.'),
    'descartar_aviso_erro': _(u'Houve um erro ao descartar as Notificações para esse Compromisso.'),
    'descendencia': _(u"Descendência"),
    'descendencia_inválida': _(u"Descendência inválida."),
    'desconta_clt': _(u"Desconta CLT?"),
    'desconta_temporario': _(u"Desconta Temporário?"),
    'descubra_cep': _(u'Descubra o CEP'),
    'descricao': _(u'Descrição'),
    'descricao_contrato': _(u'Descrição de Contrato'),
    'descricao_placa': _(u'Descrição Placa'),
    'descricao_teste': _(u'Descrição do Teste Online'),
    'desculpe_n_entendi': _(u'Desculpe, não entendi.'),
    'deseja_alterar_status_proposta': _(u"Deseja alterar o status da proposta para 'Fechado/Concluído'"),
    'desmarcar_obrigatorios': _(u'Desmarcar Obrigatórios'),
    'desmarcar_todos': _(u'Desmarcar Todos'),
    'destinatario': _(u'Destinatário'),
    'dependente': _(u'Dependente'),
    'detalhes': _(u'Detalhes'),
    'detalhes_anexo_candidato': _(u'Detalhes do Anexo do Candidato'),
    'detalhes_anexo_vaga': _(u'Detalhes do Anexo do Perfil da Vaga'),
    'detalhes_candidato': _(u'Detalhes do Candidato'),
    'detalhes_candidato_erro': _(u'Houve um erro ao trazer os Detalhes do Candidato'),
    'detalhes_cliente': _(u'Detalhes do Cliente'),
    'detalhes_compromisso': _(u'Detalhes do Compromisso'),
    'detalhes_conhec_hab_vaga': _(u'Detalhes de Conhecimento/ Habilidade do Perfil da Vaga'),
    'detalhes_contato': _(u'Detalhes do Contato'),
    'detalhes_contato_cliente': _(u'Detalhes de Contato do Cliente'),
    'detalhes_controle_acesso_cliente': _(u'Detalhes de Controle de Acesso'),
    'detalhes_consumo_plano_contratado': _(u'Detalhes de Consumo do Plano Contratado'),
    'detalhes_beneficio_cliente': _(u'Detalhes de Benefício do Cliente'),
    'detalhes_beneficio_vaga': _(u'Detalhes de Beneficio do Perfil da Vaga'),
    'detalhes_evento': _(u'Detalhes do Evento'),
    'detalhes_lembrete': _(u'Detalhes do Lembrete'),
    'detalhes_mensagem': _(u'Detalhes da Mensagem'),
    'detalhes_experiencia_candidato': _(u'Detalhes da Experiência Profissional do Candidato'),
    'detalhes_ocorrencia_cliente': _(u'Detalhes da Ocorrência do Cliente'),
    'detalhes_parecer_candidato': _(u'Detalhes do Parecer do Candidato'),
    'detalhes_plano_contratado': _(u'Detalhes do Plano Contratado'),
    'detalhes_processo_seletivo_candidato': _(u'Detalhes do Processo Seletivo do Candidato'),
    'detalhes_questionario_vaga': _(u'Detalhes do Questionário do Perfil da Vaga'),
    'detalhes_restricao': _(u'Detalhes da Restrição'),
    'detalhes_proposta_cliente': _(u'Detalhes da Proposta do Cliente'),
    'detalhes_servico_cliente': _(u'Detalhes do Serviço do Cliente'),
    'detalhes_taxa_cliente': _(u'Detalhes da Taxa do Cliente'),
    'detalhes_taxavaga_cliente': _(u'Detalhes da Taxa da Vaga do Cliente'),
    'detalhes_vaga': _(u'Detalhes de Perfil da Vaga'),
    'detalhes_restricao': _(u'Detalhes da Restrição'),
    'deve_estar_estudando': _(u'Deve estar estudando?'),
    'dezembro': _(u'Dezembro'),

    'dia': _(u'Dia'),
    'dia_atual': _(u'Dia Atual'),
    'dia_inteiro': _(u'Dia Inteiro'),
    'dia_selecionado': _(u'Dia Selecionado'),
    'dias': _(u'Dias'),
    'dias_abertos': _(u'Dias Abertos'),
    'dias_abertura_vaga': _(u'Dias de Abertura da Vaga'),
    'dias_inatividade': _(u'Dias de Inatividade'),
    'dias_uteis': _(u'Dias Úteis'),
    'dicas': _(u'Dicas'),
    'digite_parte_candidato': _('Digite parte do código, nome ou cpf'),
    'digite_parte_cliente': _('Digite parte do código, nome fantasia, razão social ou cnpj'),
    'digite_parte_vaga': _('Digite parte do código, descrição do contrato ou função'),
    'digite_parte_usuario': _('Digite parte do código ou nome'),
    'digite_cargo_da_vaga': _(u'Digite o Cargo da Vaga'),
    'digite_cidade': _(u'Digite a Cidade'),
    'digite_sua_resposta': _(u'Digite sua resposta'),
    'dissidio': _(u'Dissídio'),
    'disponivel': _(u'Disponível'),
    'disp_extra': _(u'Disponibilidade para Extra?'),
    'disp_viagem': _(u'Disponível para Viagens?'),
    'disp_internet':_(u'Disponível para Internet'),
    'disponibilidade_manha': _(u'Disponível para Manhã?'),
    'disponibilidade_tarde': _(u'Disponível para Tarde?'),
    'disponibilidade_noite': _(u'Disponível para Noite?'),
    'disponibilidade_sabado': _(u'Disponível para Sábado?'),
    'disponibilidade_domingo': _(u'Disponível para Domingo?'),
    'disp_viagem': _(u'Disponível para Viagens?'),
    'direitos_reservados': _(u".:Todos Direitos Reservados Leme Tecnologia:."),

    'documento': _(u'Documento'),
    'documentos': _(u'Documentos'),
    'documentoimpressao': _(u'Documento para Impressão'),
    'documentosimpressao': _(u'Documentos para Impressão'),
    'documentosimpressao_contrato': _(u'Documento para Contrato'),
    'documentosimpressao_duplicado': _(u"Já existe um Documento para Impressão com essa descrição."),
    'documentosimpressao_encaminhamento': _(u'Documento para Encaminhamento'),
    'documentoimpressao_nao_encontrado': _(u'O Documento para Impressão não foi encontrado.'),
    'documentoimpressao_registro_nao_encontrado': _(u' O registro base para a geração do documento não foi encontrado.'),
    'documentoimpressao_sucesso': _(u"O Documento para Impressão foi salvo com sucesso."),
    'documentos_impressao_geracao': _(u'Geração de Documentos para Impressão'),
    'documentos_impressao_geracao_sucesso': _(u'Documento gerado com sucesso.'),
    'documentos_impressao_descricao': _(u'Escolha um modelo de Documento para Impressão para ser gerado e clique em Gerar Documento.'),
    'documentos_impressao_campo_select':_(u'Selecione o modelo de Documento para Impressão a ser impresso'),
    'documento_encaminhamento_invalido': _(u'Documento para Encaminhamento inválido.'),
    'documento_contrato_invalido': _(u'Documento para Contrato inválido.'),
    'download': _(u'Download'),
    'download_arquivo': _(u'Download do Arquivo'),
    'download_anexo': _(u'Download do Anexo'),
    'domingo': _(u'Domingo'),
}
