# -*- coding:utf-8 -*-
from django.utils.translation import ugettext as _

textos_e = {
    'e': _(u'e'),
    'ead_link': _(u'Link de EAD'),
    'ead_codigo_acesso': _(u'Código EAD'),

    'edicao': _(u'Edição'),
    'edicao_candidato': _(u'Edição de Candidato'),
    'edicao_candidato_anexo': _(u'Edição de Anexo do Candidato'),
    'edicao_candidato_conhec_hab': _(u'Edição de Conhecimento/ Habilidade do Candidato'),
    'edicao_candidato_experiencia': _(u'Edição da Experiência Profissional do Candidato'),
    'edicao_candidato_parecer': _(u'Edição de Parecer do Candidato'),
    'edicao_cliente': _(u'Edição de Cliente'),
    'edicao_cliente_contato': _(u'Edição de Contato do Cliente'),
    'edicao_cliente_controle_acesso': _(u'Edição de Controle de Acesso'),
    'edicao_cliente_beneficio': _(u'Edição de Benefício do Cliente'),
    'edicao_cliente_ocorrencia': _(u'Edição de Ocorrência do Cliente'),
    'edicao_cliente_proposta': _(u'Edição de Proposta do Cliente'),
    'edicao_cliente_promotor': _(u'Edição de Promotor do Cliente'),
    'edicao_cliente_servico': _(u'Edição de Serviço do Cliente'),
    'edicao_cliente_taxa': _(u'Edição da Taxa do Cliente'),
    'edicao_cliente_taxavaga': _(u'Edição da Taxa da Vaga do Cliente'),
    'edicao_vaga': _(u'Edição de Perfil da Vaga'),
    'edicao_vaga_anexo': _(u'Edição de Anexo do Perfil da Vaga'),
    'edicao_vaga_beneficio': _(u'Edição de Benefício do Perfil da Vaga'),
    'edicao_vaga_conhec_hab': _(u'Edição de Conhecimento/ Habilidade do Perfil da Vaga'),
    'edicao_vaga_questionario': _(u'Edição do Questionário do Perfil da Vaga'),
    'editar': _(u'Editar'),
    'editar_areafuncao': _(u'Editar Área da Função.'),
    'editar_aviso_alerta': _(u'Editar Avisos ou Alertas'),
    'editar_beneficio': _(u'Editar Benefício.'),
    'editar_beneficio_cliente': _(u'Editar Benefício do Cliente.'),
    'editar_beneficio_vaga': _(u'Editar Benefício da Vaga.'),
    'editar_campo': _(u'Editar Campo'),
    'editar_candidato': _(u'Editar Candidato'),
    'editar_cand_anexo': _(u'Editar Anexo do Candidato.'),
    'editar_cand_conhec_hab': _(u'Editar Conhec./ Habilidades do Candidato.'),
    'editar_cand_experiencia': _(u'Editar Experiência do Candidato.'),
    'editar_cand_parecer': _(u'Editar Parecer do Candidato.'),
    'editar_cliente': _(u'Editar Cliente'),
    'editar_conceito': _(u'Editar Conceito de Candidato.'),
    'editar_contato_cliente': _(u'Editar Contato de Cliente.'),
    'editar_ct': _(u'Editar Habilidade Técnica.'),
    'editar_data_inativacao': _(u'Editar Data de Inativação.'),
    'editar_deficiencia': _(u'Editar Deficiência.'),
    'editar_documentoimpressao': _(u'Editar Documento para Impressão.'),
    'editar_escalact': _(u'Editar Escala de Habilidade Técnica.'),
    'editar_escolaridade': _(u'Editar Escolaridade.'),
    'editar_estadocivil': _(u'Editar Estado Civil.'),
    'editar_etapaprocsel': _(u'Editar Etapa de Processo Seletivo.'),
    'editar_etnia': _(u'Editar Etnia.'),
    'editar_familiact': _(u'Editar Família de Habilidade Técnica.'),
    'editar_filial': _(u'Editar Filial.'),
    'editar_funcao': _(u'Editar Função.'),
    'editar_formapagto': _(u'Editar Forma de Pagamento.'),
    'editar_grupoempresa': _(u'Editar Grupo de Empresa.'),
    'editar_grupousuario': _(u'Editar Grupo de Usuário.'),
    'editar_historicoocorrencia': _(u'Editar Histórico de Ocorrência.'),
    'editar_histperfilvaga': _(u'Editar Histórico de Perfil de Vaga.'),
    'editar_idioma': _(u'Editar Idioma.'),
    'editar_institutoensino': _(u'Editar Instituto de Ensino.'),
    'editar_motivoabertura': _(u'Editar Motivo de Abertura de Vaga.'),
    'editar_motivo_alteracao_status': _(u'Editar Motivo de Manutenção de Status da Vaga.'),
    'editar_multiportal': _(u'Editar Portal do Candidato.'),
    'editar_nacionalidade': _(u'Editar Nacionalidade.'),
    'editar_nivelhierarquico': _(u'Editar Nível Hierárquico.'),
    'editar_nivelexperiencia': _(u'Editar Tempo/Nível de Experiência.'),
    'editar_obstipovaga': _(u'Editar Observação do Tipo de Vaga.'),
    'editar_ocorrencia_cliente': _(u'Editar Ocorrência do Cliente.'),
    'editar_origem': _(u'Editar Origem de Candidato.'),
    'editar_pais': _(u'Editar País.'),
    'editar_portecliente': _(u'Editar Porte do Cliente.'),
    'editar_produtocliente': _(u'Editar Produto que o Cliente Consome.'),
    'editar_proposta_cliente': _(u'Editar Proposta do Cliente.'),
    'editar_ramoatividade': _(u'Editar Ramo de Atividade.'),
    'editar_recrutador': _(u'Editar Recrutador.'),
    'editar_religiao': _(u'Editar Religião.'),
    'editar_relacao': _(u'Editar Relacão.'),
    'editar_servico_cliente': _(u'Editar Serviço do Cliente.'),
    'editar_sms': _(u'Editar Mensagem de SMS.'),
    'editar_statuscliente': _(u'Editar Status do Cliente.'),
    'editar_tamanhovestuario': _(u'Editar Tamanho de Vestuário.'),
    'editar_taxa_cliente': _(u'Editar Taxa do Cliente.'),
    'editar_taxavaga_cliente': _(u'Editar Taxa da Vaga do Cliente.'),
    'editar_testes_online': _(u'Editar Teste on-line.'),
    'editar_tipocliente': _(u'Editar Tipo de Cliente.'),
    'editar_tipocandidato': _(u'Editar Tipo de Candidato.'),
    'editar_tipodocumento': _(u'Editar Tipo de Documento.'),
    'editar_tipovaga': _(u'Editar Tipo de Vaga.'),
    'editar_usuario': _(u'Editar Usuário.'),
    'editar_vaga': _(u'Editar Perfil da Vaga'),
    'editar_vaga_conh_hab': _(u'Editar Conhec./ Habilidades da Vaga.'),

    'email': _(u'E-mail'),
    'email_teste': _(u'E-mail de Teste'),
    'email_configuracao': _(u'Configuração do Servidor de E-mail'),
    'email_configuracao_invalida': _(u'Configuração do Servidor de E-mail: {}'),
    'email_destino': _(u'E-mail de Destino'),
    'email_testar': _(u'Teste de Envio de E-mail'),
    'email_testar_obrigatorio': _(u'Insira um e-mail de teste.'),
    'email_host': _(u'Host do Servidor de E-mail'),
    'email_host_user': _(u'Login do Servidor de E-mail'),
    'email_host_password': _(u'Senha do Servidor de E-mail'),
    'email_envio_habilitado': _(u'Habilitar processo de envio de E-mail'),
    'email_limite_hora': _(u'Limite de E-mails por Hora'),
    'email_origem': _(u'E-mail de Origem'),
    'email_port': _(u'Porta do Servidor de E-mail'),
    'email_remetente': _(u'E-mail de Remetente Padrão'),
    'email_resp_rh': _(u'E-mail Responsável RH'),
    'email_selecionador': _(u'E-mail do Selecionador'),
    'empresa': _(u'Empresa'),

    'encaminhado': _(u"Encaminhado"),
    'encaminhar': _(u"Encaminhar"),
    'encaminhar_candidato': _(u"Encaminhar Candidato"),
    'encaminhar_confirma': _(u"Deseja realmente encaminhar o candidato?"),
    'encaminhar_sucesso': _(u"Candidato encaminhado com sucesso."),
    'encaminhar_remover': _(u"Remover Encaminhamento"),
    'encaminhar_remover_confirma': _(u"Deseja realmente remover o encaminhamento do candidato?"),
    'encaminhar_remover_sucesso': _(u"O Encaminhamento do Candidato foi removido com sucesso."),
    'encaminhar': _(u'Encaminhar'),
    'encaminhamento': _(u'Encaminhamento'),
    'encaminhamentos': _(u'Encaminhamentos'),
    'endereco': _(u'Endereço'),
    'endereco_cobr':_(u'Endereço Cobr.'),
    'enviar': _(u'Enviar'),
    'enviar_acesso': _(u'Enviar Acesso'),
    'enviar_email': _(u'Enviar Email'),
    'enviar_mensagem': _(u'Enviar Mensagem'),
    'enviar_nova': _(u'Enviar Nova'),
    'enviar_nova_mensagem': _(u'Enviar Nova Mensagem'),
    'enviar_novo': _(u'Enviar Novo'),
    'enviar_notificacao': _(u'Enviar Notificação'),
    'enviar_notificacao_tela': _(u'Enviar Notificação de Tela'),
    'enviar_sua_mensagem': _(u'Enviar sua Mensagem'),
    'enviar_sms': _(u'Enviar Mensagem de SMS'),
    'enviar_sms_simples': _(u'Enviar SMS'),
    'enviar_sms_description': _(u'Selecione um modelo de mensagem para ser enviada.'),
    'enviar_sms_sucesso': _(u'SMS enviado com sucesso'),
    'enviar_sms_sem_servico': _(u'Sem Serviço configurado. Entre em contato com nosso departamento de suporte.'),
    'enviar_sms_sem_configuracao': _(u'Login ou senha informados não são válidas. Entre em contato com nosso departamento de suporte.'),
    'enviar_sms_sem_credito': _(u'Sem créditos para envio. Entre em contato com nosso departamento de suporte.'),
    'enviar_sms_indisponivel': _(u'O serviço de envio de SMS está indisponível no momento. Por favor, tente novamente mais tarde.'),
    'enviar_sms_celular_invalido': _(u'O número do celular do candidato não é válido. Certifique-se de que tanto o número quanto o DDD estão corretos.'),
    'envio_mala_direta': _(u'Envio de Mala Direta'),
    'envio_sms': _(u'Envio de SMS'),
    'envio_sms_limite': _(u'Limite de Envio de SMS (Quando fornecedor for Leme)'),
    'entrar': _(u"Entrar"),
    'entrevista_respondida': _(u'Todas as perguntas da entrevista foram respondidas.'),
    'entrevistador_virtual': _(u'Entrevistador Virtual'),
    'encerrar_contrato': _(u'Encerrar Contrato'),
    'encerrar_contrato_motivo': _(u'Escreva aqui o motivo de saída'),
    'encerrar_contrato_erro': _(u'Não foi possível encerrar o contrato.'),
    'encerrar_contrato_sucesso': _(u'Contrato foi encerrado com sucesso.'),
    'encerrar_contrato_confirma' : _(u'Deseja realmente encerrar o contrato com o colaborador?'),

    'equipe': _(u'Equipe'),

    'escala': _(u'Escala (Nº)'),
    'escalact': _(u'Escala de Habilidade Técnica'),
    'escalacts': _(u'Escalas de Habilidade Técnica'),
    'escalact_duplicada': _(u"Já existe uma Escala de Habilidade Técnica com essa descrição."),
    'escalact_nao_encontrada': _(u'A Escala de Habilidade Técnica não foi encontrada.'),
    'escalact_sucesso': _(u"A Escala de Habilidade Técnica foi salva com sucesso."),
    'escolaridade': _(u'Escolaridade'),
    'escolaridade_de': _(u'Escolaridade De'),
    'escolaridade_para': _(u'Escolaridade Para'),
    'escolaridades': _(u'Escolaridades'),
    'escolaridade_ini': _(u'Escolaridade Inicial'),
    'escolaridade_ini_menor_escolaridade_fin': _(u'A Escolaridade Inicial deve ser menor que a Escolaridade Final.'),
    'escolaridade_fim': _(u'Escolaridade Final'),
    'escolaridade_duplicada': _(u"Já existe uma Escolaridade com essa descrição."),
    'escolaridade_nao_encontrada': _(u'A Escolaridade não foi encontrada.'),
    'escolaridade_sucesso': _(u"A Escolaridade foi salva com sucesso."),
    'escolha_um_arquivo': _(u'Escolha um Arquivo'),
    'escreva_seu_parecer': _(u"Escreva aqui o seu parecer"),
    'especificacao': _(u'Especificação'),
    'esta_com_duvida': _(u'Está com dúvida?'),
    'esqueceu_sua_senha': _(u'Esqueceu sua senha?'),
    'estado': _(u'Estado'),
    'estado_n_informado': _(u'Estado não informado'),
    'estado_cobr': _(u'Estado Cobr.'),
    'estado_cidade': _(u'Estado/ Cidade'),
    'estado_trabalho': _(u'Estado de Trabalho'),
    'estado_civil': _(u'Estado Civil'),
    'estado_civil_de': _(u'Estado Civil De'),
    'estado_civil_para': _(u'Estado Civil Para'),
    'estados_civil': _(u'Estados Civil'),
    'estadocivil_duplicado': _(u"Já existe um Estado Civil com essa descrição."),
    'estadocivil_nao_encontrado': _(u'O Estado Civil não foi encontrado.'),
    'estadocivil_sucesso': _(u"O Estado Civil foi salvo com sucesso."),
    'estado_nascimento': _(u'Estado de Nascimento'),
    'estatistica': _('Estatística'),
    'estatisticas': _('Estatísticas'),
    'estudando': _(u'Estudando'),
    'estrangeiro': _(u'Estrangeiro'),

    'erro_upload_arquivo': _(u"Houve um erro ao realizar o upload do arquivo."),

    'etalent': _(u'Etalent'),
    'etapa': _(u'Etapa'),
    'etapaprocsel': _(u'Etapa do Processo Seletivo'),
    'etapaprocsels': _(u'Etapas do Processo Seletivo'),
    'etapaprocsel_duplicada': _(u"Já existe uma Etapa de Processo Seletivo com essa descrição."),
    'etapaprocsel_nao_encontrada': _(u'A Etapa do Processo Seletivo não foi encontrada.'),
    'etapaprocsel_sucesso': _(u"A Etapa de Processo Seletivo foi salva com sucesso."),
    'etnia': _(u'Etnia'),
    'etnias': _(u'Etnias'),
    'etnia_de': _(u'Etnia De'),
    'etnia_para': _(u'Etnia Para'),
    'etnia_duplicado': _(u"Já existe uma Etnia com essa descrição."),
    'etnia_nao_encontrado': _(u"A Etnia não foi encontrada."),
    'etnia_sucesso': _(u"A Etnia foi salva com sucesso."),

    'evento_excluir_confirmar': _(u'Deseja realmente excluir esse Evento Padrão?'),
    'evento_excluir_sucesso': _(u'O Evento Padrão foi excluído com sucesso.'),
    'evento_excluir_erro': _(u'Ocorreu um erro ao excluir o Evento Padrão.'),
    'evento_padrao': _(u'Evento Padrão'),
    'evento_padrao_copia': _(u'Cópia de Evento Padrão Para Compromisso'),
    'evento_padrao_copia_log': u"""
            O usuário criou um Compromisso de um Evento Padrão:<br>
                ({codigo}) {assunto}.<br/>
            Data: de {inicio} até {fim}
    """,
    'evento_padrao_duplicado': _(u'Já existe um Evento Padrão com esse assunto.'),
    'evento_padrao_erro_aniversario': _(u'Não é possivel criar Evento Padrão de "Lembrete de Aniversário", ele é gerado automaticamente.'),
    'evento_padrao_salvo': _(u'O Evento Padrão foi salvo com sucesso.'),
    'evento_padrao_usuario_obrigatorio': _(u'É necessário pelo menos um Usuário para salvar o Evento Padrão.'),
    'eventos_padroes': _(u'Eventos Padrões'),
    'evento_padrao_salvo': _(u'Evento Padrão salvo com sucesso.'),
    'eventos_padroes_dica': _(u'Arraste o Evento Padrão no calendário para criar um Compromisso novo.'),

    'exames': _(u'Exames'),
    'exibir_perfil_vaga': _(u'Exibir Perfil da Vaga'),
    'exigencias': _('Exigências'),
    'executar': _(u'Executar'),
    'excel': _(u'Excel(xls)'),
    'excluir': _(u'Excluir'),
    'excluir_alternativa': _(u'Excluir Alternativa'),
    'excluir_alternativa_deseja': _(u'Deseja realmente excluir a alternativa?'),
    'excluir_alternativa_sucesso': _(u'Alternativa excluída com sucesso.'),
    'excluir_areafuncao': _(u'Excluir Área da Função'),
    'excluir_areafuncao_deseja': _(u'Deseja realmente excluir a Área da Função'),
    'excluir_areafuncao_sucesso': _(u'Área da Função excluída com sucesso.'),
    'excluir_aviso_alerta': _(u'Excluir Aviso ou Alerta'),
    'excluir_aviso_alerta_deseja': _(u'Deseja realmente excluir o Aviso ou Alerta.'),
    'excluir_aviso_alerta_sucesso': _(u'Aviso ou Alerta excluído com sucesso.'),
    'excluir_beneficio': _(u'Excluir Benefício'),
    'excluir_beneficio_deseja': _(u'Deseja realmente excluir o Benefício'),
    'excluir_beneficio_sucesso': _(u'Benefício excluído com sucesso.'),
    'excluir_beneficio_cliente': _(u'Excluir Benefício do Cliente'),
    'excluir_beneficio_cliente_deseja': _(u'Deseja realmente excluir o Benefício do Cliente'),
    'excluir_beneficio_cliente_sucesso': _(u'Benefício do Cliente excluído com sucesso.'),
    'excluir_beneficio_vaga': _(u'Excluir Benefício da Vaga'),
    'excluir_beneficio_vaga_deseja': _(u'Deseja realmente excluir o Benefício da Vaga'),
    'excluir_beneficio_vaga_sucesso': _(u'Benefício da Vaga excluído com sucesso.'),
    'excluir_cand_anexo': _(u'Excluir Anexo do Candidato'),
    'excluir_cand_anexo_deseja': _(u'Deseja realmente excluir o Anexo do Candidato.'),
    'excluir_cand_anexo_sucesso': _(u'Anexo do Candidato excluído com sucesso.'),
    'excluir_cand_conh_hab': _(u'Excluir Conhec./ Habilidades do Candidato.'),
    'excluir_cand_conh_hab_deseja': _(u'Deseja realmente excluir o Conhec./ Habilidades do Candidato.'),
    'excluir_cand_conh_hab_sucesso': _(u'Conhec./ Habilidades do Candidato excluído com sucesso.'),
    'excluir_cand_experiencia': _(u'Excluir Experiência do Candidato.'),
    'excluir_cand_experiencia_deseja': _(u'Deseja realmente excluir a Experiência do Candidato.'),
    'excluir_cand_experiencia_sucesso': _(u'Experiência do Candidato excluída com sucesso.'),
    'excluir_cand_semexperiencia_deseja': _(u'Ao selecionar esse campo suas experiências serão excluídas.'),
    'excluir_cand_parecer': _(u'Excluir Parecer do Candidato.'),
    'excluir_cand_parecer_deseja': _(u'Deseja realmente excluir o Parecer do Candidato.'),
    'excluir_cand_parecer_sucesso': _(u'Parecer do Candidato excluído com sucesso.'),
    'excluir_cand_proc_sel': _(u'Excluir Processo Seletivo.'),
    'excluir_cand_proc_sel_deseja': _(u'Deseja realmente excluir o Processo Seletivo.'),
    'excluir_cand_proc_sel_sucesso': _(u'Processo Seletivo excluído com sucesso.'),
    'excluir_candidato': _(u'Excluir Candidato'),
    'excluir_cliente': _(u'Excluir Cliente'),
    'excluir_cliente_deseja': _(u'Deseja realmente excluir o Cliente'),
    'excluir_cliente_sucesso': _(u'Cliente excluído com sucesso.'),
    'excluir_cliente_deseja_lista': _(u'Ao excluir o cliente, você também irá excluir:'),
    'excluir_cliente_deseja_vagas': _(u'As vagas do cliente e todos os registros relacionados à estas vagas'),
    'excluir_conceito': _(u'Excluir Conceito de Candidato'),
    'excluir_conceito_deseja': _(u'Deseja realmente excluir o Conceito de Candidato'),
    'excluir_conceito_sucesso': _(u'Conceito de Candidato excluído com sucesso.'),
    'excluir_contato_cliente': _(u'Excluir Contato de Cliente'),
    'excluir_contato_deseja': _(u'Deseja realmente excluir o Contato de Cliente'),
    'excluir_contato_sucesso': _(u'Contato de Cliente excluído com sucesso.'),
    'excluir_controle_ip_deseja': _(u'Deseja realmente excluir o IP'),
    'excluir_controle_ip_sucesso': _(u'IP excluído com sucesso.'),
    'excluir_convivencia_deseja': _(u'Deseja realmente excluir a Convivência?'),
    'excluir_convivencia_sucesso': _(u'Convivência excluída com sucesso.'),
    'excluir_ct': _(u'Excluir Habilidade Técnica'),
    'excluir_ct_deseja': _(u'Deseja realmente excluir a Habilidade Técnica'),
    'excluir_ct_sucesso': _(u'Habilidade Técnica excluída com sucesso.'),
    'excluir_deficiencia': _(u'Excluir Deficiência'),
    'excluir_deficiencia_deseja': _(u'Deseja realmente excluir a Deficiência'),
    'excluir_deficiencia_sucesso': _(u'Deficiência excluída com sucesso.'),
    'excluir_documentoimpressao': _(u'Excluir Documento para Impressão'),
    'excluir_documentoimpressao_deseja': _(u'Deseja realmente excluir o Documento para Impressão'),
    'excluir_documentoimpressao_sucesso': _(u'Documento para Impressão excluído com sucesso.'),
    'excluir_em_massa': _(u'Excluir em Massa'),
    'excluir_escalact': _(u'Excluir Escala de Habilidade Técnica'),
    'excluir_escalact_deseja': _(u'Deseja realmente excluir a Escala de Habilidade Técnica'),
    'excluir_escalact_sucesso': _(u'Escala de Habilidade Técnica excluída com sucesso.'),
    'excluir_escolaridade': _(u'Excluir Escolaridade'),
    'excluir_escolaridade_deseja': _(u'Deseja realmente excluir a Escolaridade'),
    'excluir_escolaridade_sucesso': _(u'Escolaridade excluída com sucesso.'),
    'excluir_experiencia': _(u'Excluir Experiência Profissional'),
    'excluir_experiencia_deseja': _(u'Deseja realmente excluir a Experiência Profissional'),
    'excluir_experiencia_sucesso': _(u'Experiência Profissional excluída com sucesso.'),
    'excluir_estadocivil': _(u'Excluir Estado Civil'),
    'excluir_estadocivil_deseja': _(u'Deseja realmente excluir o Estado Civil'),
    'excluir_estadocivil_sucesso': _(u'Estado Civil excluído com sucesso.'),
    'excluir_etapaprocsel': _(u'Excluir Etapa de Processo Seletivo'),
    'excluir_etapaprocsel_deseja': _(u'Deseja realmente excluir a Etapa de Processo Seletivo'),
    'excluir_etapaprocsel_sucesso': _(u'Etapa de Processo Seletivo excluída com sucesso.'),
    'excluir_etnia': _(u'Excluir Etnia'),
    'excluir_etnia_deseja': _(u'Deseja realmente excluir a Etnia'),
    'excluir_etnia_sucesso': _(u'Etnia excluída com sucesso.'),
    'excluir_familiact': _(u'Excluir Família de Habilidade Técnica'),
    'excluir_familiact_deseja': _(u'Deseja realmente excluir a Família de Habilidade Técnica'),
    'excluir_familiact_sucesso': _(u'Família de Habilidade Técnica excluída com sucesso.'),
    'excluir_filial': _(u'Excluir Filial'),
    'excluir_filial_deseja': _(u'Deseja realmente excluir a Filial'),
    'excluir_filial_sucesso': _(u'Filial excluída com sucesso.'),
    'excluir_funcao': _(u'Excluir Função'),
    'excluir_funcao_deseja': _(u'Deseja realmente excluir a Função'),
    'excluir_funcao_sucesso': _(u'Função excluída com sucesso.'),
    'excluir_funcao_ultima_erro': _(u'Não é possível excluir a função. É obrigatório que tenha pelo menos uma.'),
    'excluir_foto': _(u'Excluir Foto'),
    'excluir_imagem': _(u'Excluir Imagem'),
    'excluir_logo': _(u'Excluir Logo'),
    'excluir_formapagto': _(u'Excluir Forma de Pagamento'),
    'excluir_formapagto_deseja': _(u'Deseja realmente excluir a Forma de Pagamento'),
    'excluir_formapagto_sucesso': _(u'Forma de Pagamento excluída com sucesso.'),
    'excluir_grupoempresa': _(u'Excluir Grupo de Empresa'),
    'excluir_grupoempresa_deseja': _(u'Deseja realmente excluir o Grupo de Empresa'),
    'excluir_grupoempresa_sucesso': _(u'Grupo de Empresa excluído com sucesso.'),
    'excluir_grupousuario': _(u'Excluir Grupo de Usuário'),
    'excluir_grupousuario_deseja': _(u'Deseja realmente excluir o Grupo de Usuário'),
    'excluir_grupousuario_sucesso': _(u'Grupo de Usuário excluído com sucesso.'),
    'excluir_historicoocorrencia': _(u'Excluir Histórico de Ocorrência'),
    'excluir_historicoocorrencia_deseja': _(u'Deseja realmente excluir o Histórico de Ocorrência'),
    'excluir_historicoocorrencia_sucesso': _(u'Histórico de Ocorrência excluído com sucesso.'),
    'excluir_histperfilvaga': _(u'Excluir Histórico de Perfil de Vaga'),
    'excluir_histperfilvaga_deseja': _(u'Deseja realmente excluir o Histórico de Perfil de Vaga'),
    'excluir_histperfilvaga_sucesso': _(u'Histórico de Perfil de Vaga excluído com sucesso.'),
    'excluir_idioma': _(u'Excluir Idioma'),
    'excluir_idioma_deseja': _(u'Deseja realmente excluir o Idioma'),
    'excluir_idioma_sucesso': _(u'Idioma excluído com sucesso.'),
    'excluir_institutoensino': _(u'Excluir Instituto de Ensino'),
    'excluir_institutoensino_deseja': _(u'Deseja realmente excluir o Instituto de Ensino'),
    'excluir_institutoensino_sucesso': _(u'Instituto de Ensino excluído com sucesso.'),
    'excluir_motivoabertura': _(u'Excluir  Motivo de Abertura de Vaga'),
    'excluir_motivoabertura_deseja': _(u'Deseja realmente excluir o  Motivo de Abertura de Vaga'),
    'excluir_motivoabertura_sucesso': _(u'Motivo de Abertura de Vaga excluído com sucesso.'),
    'excluir_motivo_alteracao_status': _(u'Excluir Motivo de Manutenção de Status da Vaga'),
    'excluir_motivo_alteracao_status_deseja': _(u'Deseja realmente excluir o  Motivo de Manutenção de Status da Vaga'),
    'excluir_motivo_alteracao_status_sucesso': _(u'Motivo de Manutenção de Status da Vaga excluído com sucesso.'),
    'excluir_multiportal': _(u'Excluir Portal do Candidato'),
    'excluir_multiportal_deseja': _(u'Deseja realmente excluir o Portal do Candidato'),
    'excluir_multiportal_sucesso': _(u'Portal do Candidato excluído com sucesso.'),
    'excluir_nacionalidade': _(u'Excluir Nacionalidade'),
    'excluir_nacionalidade_deseja': _(u'Deseja realmente excluir a Nacionalidade'),
    'excluir_nacionalidade_sucesso': _(u'Nacionalidade excluída com sucesso.'),
    'excluir_nivelexperiencia': _(u'Excluir Tempo/Nível de Experiência'),
    'excluir_nivelexperiencia_deseja': _(u'Deseja realmente excluir o Tempo/Nível de Experiência'),
    'excluir_nivelexperiencia_sucesso': _(u'Tempo/Nível de Experiência excluído com sucesso.'),
    'excluir_nivelhierarquico': _(u'Excluir Nível Hierárquico'),
    'excluir_nivelhierarquico_deseja': _(u'Deseja realmente excluir o Nível Hierárquico'),
    'excluir_nivelhierarquico_sucesso': _(u'Nível Hierárquico excluído com sucesso.'),
    'excluir_notificacao': _(u'Excluir Notificação'),
    'excluir_notificacao_deseja': _(u'Você realmente deseja excluir essa notificação?'),
    'excluir_notificacao_sucesso': _(u'Notificação excluída com sucesso'),
    'excluir_obstipovaga': _(u'Excluir Observação do Tipo de Vaga'),
    'excluir_obstipovaga_deseja': _(u'Deseja realmente excluir a Observação do Tipo de Vaga'),
    'excluir_obstipovaga_sucesso': _(u'Observação do Tipo de Vaga excluída com sucesso.'),
    'excluir_ocorrencia_cliente': _(u'Excluir Ocorrência do Cliente'),
    'excluir_ocorrencia_cliente_deseja': _(u'Deseja realmente excluir a Ocorrência do Cliente'),
    'excluir_ocorrencia_cliente_sucesso': _(u'Ocorrência do Cliente excluída com sucesso.'),
    'excluir_origem': _(u'Excluir Origem de Candidato'),
    'excluir_origem_deseja': _(u'Deseja realmente excluir a Origem de Candidato'),
    'excluir_origem_sucesso': _(u'Origem de Candidato excluída com sucesso.'),
    'excluir_pais': _(u'Excluir País'),
    'excluir_pais_deseja': _(u'Deseja realmente excluir o País'),
    'excluir_pais_sucesso': _(u'País excluído com sucesso.'),
    'excluir_palavrachave_vaga': _(u'Excluir a Palavra-chave da Vaga'),
    'excluir_palavrachave_vaga_deseja': _(u'Deseja realmente excluir a Palavra-chave da Vaga'),
    'excluir_palavrachave_vaga_sucesso': _(u'Palavra-chave da Vaga excluída com sucesso.'),
    'excluir_parecer': _(u'Excluir Parecer'),
    'excluir_parecer_deseja': _(u'Deseja realmente excluir o Parecer'),
    'excluir_parecer_sucesso': _(u'Parecer excluído com sucesso.'),
    'excluir_portecliente': _(u'Excluir Porte do Cliente'),
    'excluir_portecliente_deseja': _(u'Deseja realmente excluir o Porte do Cliente'),
    'excluir_portecliente_sucesso': _(u'Porte do Cliente excluído com sucesso.'),
    'excluir_produtocliente': _(u'Excluir Produto que o Cliente Consome'),
    'excluir_produtocliente_deseja': _(u'Deseja realmente excluir o Produto que o Cliente Consome'),
    'excluir_produtocliente_sucesso': _(u'Produto que o Cliente Consome excluído com sucesso.'),
    'excluir_proposta_anexo_deseja': _(u'Deseja realmente excluir o anexo da Proposta do Cliente'),
    'excluir_proposta_anexo_sucesso': _(u'Anexo da Proposta do Cliente excluído com sucesso.'),
    'excluir_proposta_cliente': _(u'Excluir Proposta do Cliente'),
    'excluir_proposta_cliente_deseja': _(u'Deseja realmente excluir a Proposta do Cliente'),
    'excluir_proposta_cliente_sucesso': _(u'Proposta do Cliente excluída com sucesso.'),
    'excluir_recrutador': _(u'Excluir Recrutador'),
    'excluir_recrutador_deseja': _(u'Deseja realmente excluir o Recrutador'),
    'excluir_recrutador_sucesso': _(u'Recrutador excluído com sucesso.'),
    'excluir_ramoatividade': _(u'Excluir Ramo de Atividade'),
    'excluir_ramoatividade_deseja': _(u'Deseja realmente excluir o Ramo de Atividade'),
    'excluir_ramoatividade_sucesso': _(u'Ramo de Atividade excluído com sucesso.'),
    'excluir_religiao': _(u'Excluir Religião'),
    'excluir_religiao_deseja': _(u'Deseja realmente excluir a Religião'),
    'excluir_religiao_sucesso': _(u'Religião excluída com sucesso.'),
    'excluir_relacao': _(u'Excluir Relação'),
    'excluir_relacao_deseja': _(u'Deseja realmente excluir a Relação'),
    'excluir_relacao_sucesso': _(u'Relação excluída com sucesso.'),
    'excluir_servico_anexo_deseja': _(u'Deseja realmente excluir o anexo do Serviço do Cliente'),
    'excluir_servico_anexo_sucesso': _(u'Anexo do Serviço do Cliente excluído com sucesso.'),
    'excluir_servico_cliente': _(u'Excluir Serviço do Cliente'),
    'excluir_servico_cliente_deseja': _(u'Deseja realmente excluir o Serviço do Cliente'),
    'excluir_servico_cliente_sucesso': _(u'Serviço do Cliente excluído com sucesso.'),
    'excluir_sms': _(u'Excluir Mensagem de SMS'),
    'excluir_sms_deseja': _(u'Deseja realmente excluir a Mensagem de SMS'),
    'excluir_sms_sucesso': _(u'Mensagem de SMS excluída com sucesso.'),
    'excluir_statuscliente': _(u'Excluir Status do Cliente'),
    'excluir_statuscliente_deseja': _(u'Deseja realmente excluir o Status do Cliente'),
    'excluir_statuscliente_sucesso': _(u'Status do Cliente excluído com sucesso.'),
    'excluir_tamanhovestuario': _(u'Excluir Tamanho de Vestuário'),
    'excluir_tamanhovestuario_deseja': _(u'Deseja realmente excluir o Tamanho de Vestuário'),
    'excluir_tamanhovestuario_sucesso': _(u'Tamanho de Vestuário excluído com sucesso.'),
    'excluir_taxa_cliente': _(u'Excluir Taxa do Cliente'),
    'excluir_taxa_cliente_deseja': _(u'Deseja realmente excluir a Taxa do Cliente'),
    'excluir_taxa_cliente_sucesso': _(u'Taxa do Cliente excluída com sucesso.'),
    'excluir_taxavaga_cliente': _(u'Excluir Taxa da Vaga do Cliente'),
    'excluir_taxavaga_cliente_deseja': _(u'Deseja realmente excluir a Taxa da Vaga do Cliente'),
    'excluir_taxavaga_cliente_sucesso': _(u'Taxa da Vaga do Cliente excluída com sucesso.'),
    'excluir_testes_online': _(u'Excluir Teste on-line'),
    'excluir_testes_online_deseja': _(u'Deseja realmente excluir o Teste on-line'),
    'excluir_testes_online_sucesso': _(u'Teste on-line excluído com sucesso.'),
    'excluir_tipocandidato': _(u'Excluir Tipo de Candidato'),
    'excluir_tipocandidato_deseja': _(u'Deseja realmente excluir o Tipo de Candidato'),
    'excluir_tipocandidato_sucesso': _(u'Tipo de Candidato excluído com sucesso.'),
    'excluir_tipocliente': _(u'Excluir Tipo de Cliente'),
    'excluir_tipocliente_deseja': _(u'Deseja realmente excluir o Tipo de Cliente'),
    'excluir_tipocliente_sucesso': _(u'Tipo de Cliente excluído com sucesso.'),
    'excluir_tipodocumento': _(u'Excluir Tipo de Documento'),
    'excluir_tipodocumento_deseja': _(u'Deseja realmente excluir o Tipo de Documento'),
    'excluir_tipodocumento_sucesso': _(u'Tipo de Documento excluído com sucesso.'),
    'excluir_tipovaga': _(u'Excluir Tipo de Vaga'),
    'excluir_tipovaga_deseja': _(u'Deseja realmente excluir o Tipo de Vaga'),
    'excluir_tipovaga_sucesso': _(u'Tipo de Vaga excluído com sucesso.'),
    'excluir_todos_cands_os_filtrados': _(u'Excluir todos os Candidatos Filtrados'),
    'excluir_usuario': _(u'Excluir Usuário'),
    'excluir_usuario_deseja': _(u'Deseja realmente excluir o Usuário'),
    'excluir_usuario_sucesso': _(u'Usuário excluído com sucesso.'),
    'excluir_vaga': _(u'Excluir Vaga'),
    'excluir_vaga_deseja': _(u'Deseja realmente excluir a Vaga'),
    'excluir_vaga_sucesso': _(u'Vaga excluída com sucesso.'),
    'excluir_vaga_anexo': _(u'Excluir Anexo do Perfil da Vaga'),
    'excluir_vaga_anexo_deseja': _(u'Deseja realmente excluir o Anexo do Perfil da Vaga'),
    'excluir_vaga_anexo_sucesso': _(u'Anexo do Perfil da Vaga excluído com sucesso.'),
    'excluir_vaga_conh_hab': _(u'Excluir Conhec./ Habilidades da Vaga.'),
    'excluir_vaga_conh_hab_deseja': _(u'Deseja realmente excluir o Conhec./ Habilidades da Vaga.'),
    'excluir_vaga_conh_hab_sucesso': _(u'Conhec./ Habilidades da Vaga excluído com sucesso.'),
    'excluir_vaga_questionario': _(u'Excluir Questionário da Vaga.'),
    'excluir_vaga_quest_deseja': _(u'Deseja realmente excluir o Questionário da Vaga.'),
    'excluir_vaga_quest_sucesso': _(u'Questionário da Vaga excluído com sucesso.'),
    'exclusao_forcada': _(u'Exclusão Forçada'),
    'exclusao_forcada_confirmacao': _(u'Deseja realmente Excluir o registro selecionado? Esta ação não poderá ser desfeita.'),
    'exclusao_forcada_info': _(u'Você pode excluir alguns registros que não são habilitados nos cadastros normais. Selecione o tipo e o registro para realizar a exclusão.'),
    'exclusao_forcada_selecao': _(u'Selecione o tipo e o registro para exclusão'),
    'exclusao_forcada_sucesso': _(u'Exclusão Forçada realizada com sucesso.'),
    'exibir_meus_pareceres': _(u'Exibir apenas os meus pareceres'),
    'experiencia': _(u"Experiência"),
    'experiencias': _(u"Experiências"),
    'experiencia_nenhuma': _(u"Nenhuma experiência cadastrada."),
    'experiencia_profissional': _(u'Experiência Profissional'),
    'experiencias_profissionais': _(u'Experiências Profissionais'),
    'experiencia_candidato': _(u'Experiência do Candidato'),
    'experiencias_candidato': _(u'Experiências do Candidato'),
    'experiencia_candidato_nao_encontrado': _(u'A Experiência do Candidato não foi encontrada.'),
    'experiencia_candidato_sucesso': _(u"A Experiência do Candidato foi salva com sucesso."),
    'experiencias_limpar_deseja': _(u'Deseja realmente marcar "Sem Experiência"? Todas as experiências cadastradas serão apagadas.'),
    'experiencias_n_preenchidas': _(u'Existem experiências não preenchidas. Para adicionar outras, preencha primeiro as adicionadas.'),
    'experiencias_limpar_sucesso': _(u'Todas as Experiências foram apagadas.'),
    'exportacao_senior': _(u'Exportação – Modelo Sênior'),
    'exportar_senior_trava': _(u'Deseja que a Exportação para a Sênior trave os campos em branco?'),
    'exportacao_gi': _(u'Exportação – Modelo GI'),
    'exportacoes': _(u'Exportações'),
    'exportar': _(u'Exportar'),
    'extracurricular': _(u'Extracurricular'),

}
