from django.utils.translation import ugettext as _

textos_f = {
    'facebook_application_id': _("Application ID"),
    'facebook_secret_key': _("Secret KEY"),
    'facebook_namespace': _("Namespace"),
    'faixa_etaria': _(u'Faixa Etária'),
    'faltam': _(u'Faltam'),
    'familia': _(u'Família'),
    'familiact': _(u'Família de Habilidade Técnica'),
    'familiacts': _(u'Famílias de Habilidade Técnica'),
    'familiact_duplicada': _(u"Já existe uma Família de Habilidade Técnica com essa descrição."),
    'familiact_nao_encontrada': _(u'A Familia de Habilidade Técnica não foi encontrada.'),
    'familiact_sucesso': _(u"A Família de Habilidade Técnica foi salva com sucesso."),
    'falha_excluir_registro': _(u'Falha ao excluir o registro. Entre em contato com o suporte.'),
    'fale_conosco' : _(u'Fale Conosco'),
    'fase_processo_seletivo' : _(u'Fase do Processo Seletivo'),
    'fases_processo_seletivo' : _(u'Fases do Processo Seletivo'),
    'fase_proc_sel' : _(u'Fase do Proc. Sel.'),
    'faturado': _(u'Faturado'),
    'faturamento_anual': _(u'Faturamento Anual'),
    'faturamento_candidatos': _(u'Faturamento de Candidatos'),
    'faturamento_candidatos_descricao': _(u'Consulte e gerencie o faturamento dos Candidatos aprovados.'),
    'faturamento_candidatos_faturar_sucesso': _(u'Faturamento salvo com sucesso.'),
    'faturamento_candidatos_faturar_erros': _(u'Houve um erro ao salvar o faturamento.'),
    'favoritos': _(u'Favoritos'),
    'fazer_pesquisa_lista': _(u'Fazer Pesquisa por Lista'),
    'fax': _(u'Fax'),

    'feedbacks': _(u'Feedbacks'),
    'fechar': _(u'Fechar'),
    'fechar_vaga_confirmar': _(u'A Vaga já atingiu a quantidade solicitada. Deseja fechar?'),
    'fechadas': _(u'Fechadas'),
    'fechadas_parcial': _(u'Fechadas Parcial'),
    'fechamento_vaga': _(u'Fechamento da Vaga'),
    'feminino': _(u'Feminino'),
    'fevereiro': _(u'Fevereiro'),

    'fila_candidatura': _(u'Fila de Candidatura'),
    'fila_candidatura_descricao': _(u'Consulta os Candidatos que realizaram candidaturas nas vagas cadastradas.'),
    'fila_candidatura_remover': _(u'Remover da Fila de Candidatura'),
    'fila_candidatura_remover_confirma': _(u'Deseja realmente remover o candidato da Fila de Candidatura?'),
    'fila_candidatura_remover_sucesso': _(u'O Candidato foi removido da Fila de Candidatura.'),
    'fila_selecao': _(u'Fila de Seleção'),
    'fila_selecao_descricao': _(u'''Consulta os Candidatos que estão na Fila de Seleção para as vagas.'''),
    'fila_selecao_remover': _(u'Remover da Fila de Seleção'),
    'fila_selecao_remover_confirma': _(u'Deseja realmente remover o candidato da Fila de Seleção?'),
    'fila_selecao_remover_sucesso': _(u'O Candidato foi removido da Fila de Seleção.'),
    'fila_selecao_adicionar_confirm': _(u"Deseja Realmente adicionar o candidato na Fila de Seleção?"),
    'fila_selecao_adicionar_sucesso': _(u"O Candidato foi adicionado na Fila de Seleção com sucesso."),
    'fila_selecao_ja_adicionado': _(u"O Candidato já esta na Fila de Seleção."),
    'filial': _(u'Filial'),
    'filiais': _(u'Filiais'),
    'filial_cliente': _(u'Filial do Cliente'),
    'filial_duplicada': _(u"Já existe uma Filial com essa descrição."),
    'filial_nao_encontrada': _(u'A Filial não foi encontrada.'),
    'filial_sucesso': _(u"A Filial foi salva com sucesso."),
    'filhos_com_brasileiro': _(u'Filhos com Brasileiro'),
    'filtrar': _(u'Filtrar'),
    'filtros': _(u'Filtros'),
    'filtros_para_selecao': _(u'Filtros para Seleção'),
    'filtros_selecao_candidato': _(u'Filtros da Seleção de Candidatos'),
    'filtros_selecao_candidato_descricao': _(u'Gerencie os filtros que ficarão visíveis na Seleção de Candidatos. O usuário ainda terá acesso aos filtros ocultos caso utilize o "Gerenciar Filtros".'),
    'filtros_selecao_candidato_sucesso': _(u'Os filtros foram salvos com sucesso.'),
    'filtros_selecao_candidato_log': _(u'Os seguintes campos foram selecionados: {}'),
    'fisica': _(u'Física'),

    'folha_pagamento': _(u'Folha de Pagamento'),
    'foto': _(u'Foto'),
    'foto_candidato': _(u'Foto do Candidato'),
    'foto_excluir_confirm': _(u'Deseja realmente excluir a foto?'),
    'foto_excluir_erro':_(u'Houve um erro ao excluir a foto.'),
    'foto_excluir_sucesso': _(u'Foto excluída com sucesso.'),
    'foto_obrigatoria': _(u'Foto Obrigatória'),
    'foto_n_encontrada':_(u'Não foi possível encontrar a foto.'),
    'foto34': _(u'Foto (3x4)'),
    'fotos': _(u'Fotos'),
    'fotos_perfil': _(u'Foto do Perfil'),
    'fotobook_tamanho_aviso': _(u'As fotos devem ter até 404px de altura e até 404px de largura.'),
    'fotobook_substituicao_aviso': _(u'As fotos são salvas automaticamente após o recorte. Ao inserir uma nova foto, a existente será substituida.'),
    'fotobook_obg': _(u'É necessário inserir todas as fotos para salvar.'),
    'fotobook_remocao_termo_aviso': _(u'Caso o termo seja rejeitado, as fotos serão removidas. Deseja realmente remover todas as fotos?'),
    'formacao': _(u'Formação'),
    'formacao_academica': _(u'Formação Acadêmica'),
    'formacao_extra': _(u'Formação Extracurricular'),
    'formapagto': _(u'Forma de Pagamento'),
    'formapagtos': _(u'Formas de Pagamento'),
    'formapagto_duplicado': _(u"Já existe uma Forma de Pagamento com essa descrição."),
    'formapagto_nao_encontrada': _(u'A Forma de Pagamento não foi encontrada.'),
    'formapagto_sucesso': _(u"A Forma de Pagamento foi salva com sucesso."),
    'formatos_permitidos': _(u'Formatos permitidos: {}'),
    'formatos_permitidos_pdfdoctxt': _(u'Formatos permitidos: DOC, PDF e TXT.'),
    'formulario_cand_portal': _(u'Campos Disponíveis no Formulário de Cadastro de Candidato'),
    'fornecido_por': _(u'Fornecido Por'),

    'fumante': _(u'Fumante'),
    'funcao': _(u'Função'),
    'funcoes_apto': _(u'Funções que estou apto a exercer (É obrigatório pelo menos uma)'),
    'funcoes_apto_validar': _(u'É obrigatório pelo menos uma função.'),
    'funcoes_apto_duplicadas': _(u'Esta função já foi selecionada anteriormente.'),
    'funcoes_apto_n_preenchidas': _(u'Existem funções não preenchidas. Para adicionar outras, preencha primeiro as adicionadas.'),
    'funcao_de': _(u'Função De'),
    'funcao_para': _(u'Função Para'),
    'funcao_inicial': _(u"Função Inicial"),
    'funcao_inicial_obrigatoria': _(u"A Função Inicial é obrigatória."),
    'funcao_final': _(u"Função Final"),
    'funcao_final_obrigatoria': _(u"A Função Final é obrigatória."),
    'funcoes': _(u'Funções'),
    'funcao_duplicada': _(u"Já existe uma Função com essa descrição."),
    'funcao_exercida': _(u'Funções Exercida'),
    'funcao_nao_encontrada': _(u'A Função não foi encontrada.'),
    'funcao_sucesso': _(u"A Função foi salva com sucesso."),
    'funcao_obrigatoria': _(u"A Função é obrigatória."),
    'funcoes_cand_duplicadas': _(u'Esta Função já esta adicionada ao seu cadastro.'),
    'funcoes_pretendidas': _(u'Funções Pretendidas'),

    'fonetica': _(u"Fonética"),

    'fuso_horario': _(u'Fuso Horário'),
}
