# -*- coding:utf-8 -*-
from django.utils.translation import ugettext as _

textos_h = {
    'habilidade_tecnica': _(u'Habilidade Técnica'),
    'habilidades_tecnicas': _(u'Habilidades Técnicas'),
    'habilidade_tecnica_invalida': _(u'Habilidade Técnica inválida.'),
    'habilidade_tecnica_duplicada':  _(u"Já existe uma Habilidade Técnica com essa descrição."),
    'habilidade_tecnica_nao_encontrada': _(u'A Habilidade Técnica não foi encontrada.'),
    'habilidade_tecnica_sucesso': _(u"A Habilidade Técnica foi salva com sucesso."),
    'habilitacao': _(u'Habilitação'),
    'habilitacao_invalida': _(u'Habilitação inválida.'),
    'habilitacao_validade': _(u'Data de Validade da CNH'),
    'habilitacao_validade_invalida': _(u'Data de Validade da CNH inválida.'),
    'habilitar_campos_gi_portal_cli': _(u'Habilitar edição dos campos Empresa e Unidade'),
    'habilitar_campos_gi_portal_cli_help_text': _(u'Marque caso queira que o Cliente edite a Empresa e Unidade ao aprovar o candidato pelo Portal do Cliente. Caso não seja marcado, o sistema irá salvar os valores padrões "1" para ambos os campos.'),
    'historico': _(u'Histórico'),
    'historico_ocorrencia': _(u'Histórico de Ocorrência'),
    'historicos_ocorrencias': _(u'Históricos de Ocorrência'),
    'historicoocorrencia_duplicado': _(u"Já existe um Historico de Ocorrência com essa descrição."),
    'historicoocorrencia_nao_encontrado': _(u'O Histórico de Ocorrência não foi encontrado.'),
    'historicoocorrencia_sucesso': _(u"O Histórico de Ocorrência foi salvo com sucesso."),
    'histperfilvaga': _(u'Histórico de Perfil de Vaga'),
    'histperfilvagas': _(u'Históricos de Perfil de Vaga'),
    'histperfilvaga_duplicado': _(u"Já existe um Histórico de Perfil de Vaga com essa descrição."),
    'histperfilvaga_nao_encontrado': _(u'O Histórico de Perfil de Vaga não foi encontrado.'),
    'histperfilvaga_sucesso': _(u"O Histórico de Perfil de Vaga foi salvo com sucesso."),
    'hoje_agenda_tooltip': _(u'Ir para o Dia Atual'),
    'home': _(u'Home'),
    'hora': _(u'Hora'),
    'hora_extra': _(u'Hora Extra'),
    'hora_noturna': _(u'Hora Noturna'),
    'hora_extra_noturna': _(u'Hora Extra Noturna'),
    'hora_9999': _(u'Hora (99:99)'),
    'hora_invalida': _(u'Hora inválida'),
    'hora_inicial_util': _(u'Horário Comercial Inicial'),
    'hora_final_util': _(u'Horário Comercial Final'),
    'horas': _(u'Horas'),
    'horario': _(u'Horário'),
    'horarios': _(u'Horários'),
    'horario_adminstrativo': _(u'Horário Administrativo'),
    'horario_atendimento_candidato': _(u'Horário de Atendimento ao Candidato'),
    'horario_candidatura': _(u'Horário de Candidatura'),
    'horario_exigencia': _(u'Horário/Exigência'),
    'horario_operacional': _(u'Horário Operacional'),
    'horario_trab': _(u'Horário de Trabalho'),
    'horario_trab_invalido': _(u'Horário de Trabalho inválido.'),
    'horario_turno': _(u'Horário do Turno.'),
    'horario_contato': _(u'Melhor Horário de Contato'),
    'hora': _(u'Hora'),
    'horas': _(u'Horas'),
    'horas_mes': _(u'Horas no Mês'),
    'horas_mes_invalida': _(u'Horas no Mês inválidas.'),
    'horas_semana': _(u'Horas na Semana'),
    'houve_erro_tentar_conexao': _(u"Houve um erro ao tentar conexão."),
    'html_botao_pagseguro': _(u'Html botão Integração PagSeguro'),
    'html_botao_pagseguro_req_vaga': _(u'Html botão Integração PagSeguro para Requerimento de Vaga'),
}
