# -*- coding:utf-8 -*-
from django.utils.translation import ugettext as _

textos_m = {
    'mae': _(u'Nome da Mãe'),
    'manutencao_vaga': _(u'Manutenção de Vagas'),
    'manutencao_vaga_sucesso': _(u'Manutenção da Vagas realizada com sucesso.'),
    'manutencao_vaga_status': _(u'Manutenção de Vagas por Status'),
    'manutencao_vaga_sem_status_alerta': _(u'Você não tem permissão para nenhum Status de Vaga disponível. Não é possível realizar manutenção em nenhuma vaga. Entre em contato com o Administrador do Sistema'),
    'manutencao_vaga_observacao_obrigatoria': _(u'Observações Obrigatórias'),
    'manutencao_processo_seletivo': _(u'Manutenção do Processo Seletivo'),
    'manutencao_processo_seletivo_sucesso': _(u'Manutenção do Processo Seletivo realizada com sucesso.'),
    'manutencao_processo_seletivo_sem_permissao': _(u'Acesso negado para a Manutenção do Processo Seletivo.'),
    'mapa_contato_cliente': _(u'Mapa de Contato com Cliente'),
    'marcar_disponiveis': _(u'Marcar Disponíveis'),
    'marcar_todos': _(u'Marcar Todos'),
    'marcar_desmarcar_todos': _(u'Marcar/ Desmarcar Todos'),
    'marco': _(u'Março'),
    'mais_zoom':_(u'Mais Zoom'),
    'maio': _(u'Maio'),
    'masculino': _(u'Masculino'),

    'media': _(u'Média'),
    'menos_zoom':_(u'Menos Zoom'),
    'mensagem': _(u'Mensagem'),
    'mensagens': _(u'Mensagens'),
    'mensgaem_cadastro_descricao': _(u'Envie aqui uma mensagem para um usuário do SPA.'),
    'mensagem_enviada': _(u"Mensagem enviada com sucesso."),
    'membros': _(u'Membros'),
    'mes': _(u"Mês"),
    'mes_ano': _(u"Mês/ Ano"),
    'meses_pico_producao': _(u"Meses com Pico de Produção"),
    'meu_curriculo': _(u'Meu Currículo'),
    'meus_compromissos': _(u'Meus Compromissos'),

    'minimo_aceitavel': _(u'Mínimo Aceitável'),
    'minha_fila_selecao': _(u'Minha Fila de Seleção'),
    'minhas_candidaturas': _(u'Minhas Candidaturas'),
    'minhas_mensagens': _(u'Minhas Mensagens'),
    'minhas_requisicoes_vaga':_(u'Minhas Requisições de Vagas'),
    'minhas_vagas': _(u'Minhas Vagas'),
    'minhas_vagas_aberto': _(u'Minhas Vagas em Aberto'),
    'minutos': _(u'Minutos'),
    'minuto_cada_1': _(u'A cada 1 minuto'),
    'minuto_cada_2': _(u'A cada 2 minutos'),
    'minuto_cada_5': _(u'A cada 5 minutos'),
    'minuto_cada_10': _(u'A cada 10 minutos'),
    'minuto_cada_nunca': _(u'Nunca'),

    'modelo_carro': _(u'Modelo do Carro'),
    'modelo_placa': _(u'Modelo da Placa'),
    'modulo': _(u'Módulo'),
    'modulo_fotos': _(u'Módulo de Fotos'),
    'modulo_fotos_help': _(u'Configure abaixo as legendas para os tipos das fotos que deseja solicitar ao candidato.'),
    'modulos_adicionais': _(u'Módulos Adicionais'),
    'modulos_contratados': _(u"Módulos Contratados"),
    'mostra_portal_cliente': _(u'Mostrar no Portal do Cliente?'),
    'mostrar_estatisticas': _(u'Mostrar Estatísticas'),
    'mostrar_clientes': _(u'Mostrar Painel de Clientes (Apenas os clientes que tiverem Logo)'),
    'mostrar_lista_vagas': _(u'Mostrar Lista de Últimas Vagas'),
    'motivo': _(u'Motivo'),
    'motivo_abertura': _(u'Motivo de Abertura'),
    'motivoabertura': _(u'Motivo de Abertura de Vaga'),
    'motivoaberturas': _(u'Motivos de Abertura de Vaga'),
    'motivoabertura_duplicado': _(u"Já existe um Motivo de Abertura de Vaga com essa descrição."),
    'motivoabertura_nao_encontrado': _(u'O Motivo de Abertura de Vaga não foi encontrado.'),
    'motivoabertura_sucesso': _(u"O Motivo de Abertura de Vaga foi salvo com sucesso."),
    'motivo_alteracao': _(u'Motivo de Manutenção'),
    'motivo_alteracao_status': _(u'Motivo de Manutenção de Status da Vaga'),
    'motivo_alteracao_statuss': _(u'Motivos de Manutenção de Status da Vaga'),
    'motivo_alteracao_status_duplicado': _(u"Já existe um Motivo de Manutenção de Status da Vaga com essa descrição."),
    'motivo_alteracao_status_nao_encontrado': _(u'O Motivo de Cancelamento de Vaga não foi encontrado.'),
    'motivo_alteracao_status_sucesso': _(u"O Motivo de Manutenção de Status da Vaga foi salvo com sucesso."),
    'motivo_saida': _(u'Motivo de Saída'),
    'motivo_segurancao_requisicao_rejeitada_bne': _(u'''Por motivo de segurança
        a requisição foi rejeitada. Solicitamos que entre em contato com o
        0800 41 2400 e valide seu acesso.'''),
    'mover': _(u'Mover'),
    'movimentacao_funcional': _(u'Movimentação Funcional'),
    'movimentacao_funcional_erro': _(u'Não foi possível realizar a Movimentação Funcional.'),
    'movimentacao_funcional_sucesso': _(u'Movimentação Funcional foi realizada com sucesso.'),
    'movimentacao_funcional_confirma' : _(u'Deseja realmente mudar a função do colaborador?'),

    'multiportais': _(u'Multiplos Portais'),
    'multiportal_limite_atingido': _(u"Limite máximo de Portais atingido."),
    'multiportal_duplicado': _(u"Já existe um Portal do Candidato com esse nome."),
    'multiportal_nao_encontrado': _(u'O Portal do Candidato não foi encontrado.'),
    'multiportal_sucesso': _(u"O Portal do Candidato foi salvo com sucesso."),

}
