# -*- coding:utf-8 -*-
from django.utils.translation import ugettext as _

textos_n = {
    'n_agencia': _(u'Nº Agência'),
    'n_conta': _(u'Nº Conta'),
    'n_filhos': _(u'Nº de Filhos'),
    'n_estagio': _(u'Nº Estagiários'),
    'n_funcionario': _(u'Nº Funcionários'),
    'n_temporario': _(u'Nº Temporários'),
    'n_tercerizado': _(u'Nº Terceirizados'),
    'n_sus': _(u'Nº do SUS'),

    'nacional': _(u'Nacional'),
    'nacionalidade': _(u'Nacionalidade'),
    'nacionalidades': _(u'Nacionalidades'),
    'nacionalidade_duplicada': _(u"Já existe uma Nacionalidade com essa descrição."),
    'nacionalidade_nao_encontrada': _(u'A Nacionalidade não foi encontrada.'),
    'nacionalidade_sucesso': _(u"A Nacionalidade foi salva com sucesso."),
    'nao': _(u'Não'),
    'nao_foi_possivel_obter_funcoes': _(u"Não foi possivel obter as funções"),
    'nao_informado': _(u'Não Informado'),
    'nao_entrevistado': _(u'Não Entrevistado'),
    'nao_publicada': _(u'Nao Publicada'),
    'nascido': _(u'Nascido'),

    'nenhuma': _(u'Nenhuma'),
    'nenhuma_informada': _(u'Nenhuma Informada'),
    'nenhum_informado': _(u'Nenhum Informado'),

    'nivel': _(u'Nível'),
    'nivel_de': _(u'Nível De'),
    'nivel_para': _(u'Nível Para'),
    'nivel_desejado': _(u"Nível Desejado"),
    'nivelexperiencia': _(u'Tempo/Nível de Experiência'),
    'nivelexperiencia_ini': _(u'Nível de Experiência Inicial'),
    'nivelexperiencia_fin': _(u'Nível de Experiência Final'),
    'nivelexperiencia_de': _(u'Tempo/Nível de Experiência De'),
    'nivelexperiencia_para': _(u'Tempo/Nível de Experiência Para'),
    'nivelexperiencia_duplicado': _(u"Já existe um Nível com essa descrição."),
    'nivelexperiencia_tempo_duplicado': _('Já existe um Tempo com esse valor.'),
    'nivelexperiencia_nao_encontrado': _(u'Tempo/Nível de Experiência não foi encontrado.'),
    'nivelexperiencia_sucesso': _(u"O Tempo/Nível foi salvo com sucesso."),
    'nivel_exp_ini_menor_nivel_exp_fin': _(u'O Nível de Experiência Inicial deve ser menor que o Nível de Experiência Final.'),
    'nivel_gerencia':_(u'Nível Gerência'),
    'nivel_gerencias':_(u'Níveis Gerência'),
    'nivel_hierarquico': _(u'Nível Hierárquico'),
    'nivel_hierarquicos': _(u'Níveis Hierárquicos'),
    'nivel_hierarquico_duplicado': _(u"Já existe um Nível Hierárquico com essa descrição."),
    'nivelhierarquico_nao_encontrado': _(u'Nível Hierárquico não foi encontrado.'),
    'nivel_hierarquico_sucesso': _(u"O Nível Hierárquico foi salvo com sucesso."),
    'nivel_hierarquico_vaga': _(u'Nível Hierárquico da Vaga'),
    'nivel_hierarquicos_vaga': _(u'Níveis Hierárquicos da Vaga'),

    'no': _(u'Nº'),
    'no_cobr':_(u'Nº Cobr.'),
    'no_cookies': _(u'''
       Parece que seu navegador não tem cookies
       habilitados. Cookies são necessários para o login.
    '''),
    'no_dias_temporaria': _(u'Nº de Dias p/ Vaga Temporária'),
    'nome': _(u'Nome'),
    'nome_arquivo': _(u'Nome do Arquivo'),
    'nome_candidato': _(u'Nome do Candidato'),
    'nome_completo': _(u'Nome Completo'),
    'nome_curso': _(u'Nome do Curso'),
    'nome_imagem': _(u"Nome da Imagem"),
    'nome_fantasia': _(u'Nome Fantasia'),
    'nome_fantasia_nome': _(u'Nome Fantasia/ Nome'),
    'nome_filhos': _(u'Nome dos Filhos'),
    'nome_primeiro': _(u'Primeiro Nome'),
    'normal': _(u'Normal'),
    'nota': _(u'Nota'),
    'nota_maxima': _(u'Nota Máxima'),
    'notificado': _(u"Notificado"),
    'notificacoes': _(u"Notificações"),
    'notificacoes_compromissos': _(u'Notificações de Compromissos'),
    'notificacao_lida': _(u'Lida'),
    'notificacao_nao_lida': _(u'Não Lida'),
    'notificacao_mudar_status': _(u'Mudar Status (Lida/ Não Lida)'),
    'nova_alternativa': _(u'Nova Alternativa'),
    'nova_funcao': _(u'Nova Função'),
    'nova_experiencia': _(u'Nova Experiência'),
    'nova_selecao': _(u'Nova Seleção'),
    'nova_requisicao':_(u'Nova Requisição'),
    'novas_candidaturas':_(u'Novas Candidaturas'),
    'novas_candidaturas_parceiros':_(u'Novas Candidaturas do Parceiros'),
    'novas_mensagens':_(u'Novas Mensagens'),
    'novas_requisicoes_vaga':_(u'Novas Requisições de Vagas'),
    'novas_vagas':_(u'Novas Vagas'),
    'novembro': _(u'Novembro'),
    'novo':_(u'Novo'),
    'novos':_(u'Novos'),
    'novo_candidato':_(u'Novo candidato'),
    'novo_compromisso':_(u'Novo Compromisso'),
    'novo_idioma': _(u"Novo Idioma"),
    'novo_integrante':_(u'Novo Integrante'),
    'novo_recrutador': _(u'Novo Recrutador'),
    'novo_produto': _(u'Novo Produto'),
    'novo_portal': _(u'Novo Portal'),
    'novos_contatos_cliente': _(u'Novos Contatos do Cliente'),
    'novos_contatos_cliente_ocorrencia': _(u'Novos Contatos do cliente - Ocorrência'),
    'novos_compromissos':_(u'Novos Compromissos'),
    'nossos_clientes': _(u'Nossos Clientes'),

    'numero': _(u'Número'),
    'numero_contrato': _(u'Número do Contrato'),
    'numero_proposta': _(u'Número da Proposta'),
    'numero_serie': _(u'Nº de Serie'),
    'numero_vaga': _(u'N° da Vaga'),
}
