# -*- coding:utf-8 -*-
from django.utils.translation import ugettext as _

textos_p = {
    'paineis': _(u'Painéis'),
    'paineis_estatisticos': _(u'Painéis Estatísticos'),
    'painel_candidatos': _(u'Painel de Candidatos'),
    'painel_clientes': _(u'Painel de Clientes'),
    'painel_vagas': _(u'Painel de Vagas'),
    'pai': _(u'Nome do Pai'),
    'pais': _(u'País'),
    'pais_duplicada': _(u"Já existe um País com essa descrição."),
    'pais_padrao': _(u'País Padrão?'),
    'pais_padrao_cadastrado': _('Já existe um país padrão cadastrado no sistema.'),
    'pais_sigla_duplicada': _(u"Já existe um País com essa sigla."),
    'pais_sucesso': _(u"O País foi salvo com sucesso."),
    'paises': _(u'Paises'),
    'pais_nao_encontrado': _(u'O País não foi encontrado.'),
    'pagamentos': _(u'Pagamentos'),
    'pagseguro_habilitado': _(u'Apresentar Formulário Premium'),

    'palavra_chave': _(u'Palavra(s)-chave'),
    'palavra_chave_duplicada': _(u'Já existe uma Palavra-chave com essa descrição.'),
    'palavra_chave_texto1': _(u'''A busca por palavra-chave deve ser utilizada quando desejar buscar palavras específicas que não
    possuem um campo para filtrá-las e palavras que possam ter no cadastro ou no currículo anexo,
    como por exemplo: "Word", "Excel", "AUTOCAD", "Solda MIG", "Mopp".
    '''),
    'palavra_chave_texto2': _(u'''Dependendo da forma que digitar as palavras-chave, o sistema irá realizar a busca de uma forma
    diferente usando a operação "E", "OU", ou a busca exata do termo " ", conforme abaixo:
    '''),
    'palavra_chave_vaga': _(u'Palavra(s)-chave da Vaga'),
    'para_invalido': _('O campo Para inválido.'),

    'parametros_implantacao': _(u'Parâmetros de Implantação'),
    'parametros_implantacao_sucesso': _(u'Parâmetros de Implantação salvo com sucesso.'),
    'parametros_implantacao_desc': _(u'''Habilite e Gerencie Módulos e Configurações do Cliente.'''),
    'parametros_feedback_01_lbl': _(u'Configuração de Mensagem de Feedback para a Inserção do Candidato no Processo Seletivo'),
    'parametros_feedback_01_help': _(u'Ao Inserir o Candidato da Fila de Candidatura no Processo Seletivo (Envio de E-mail Somente ao Candidato Inserido no Processo Seletivo)'),
    'parametros_feedback_02_lbl': _(u'Configuração de Mensagem de Feedback para a Remoção do Candidato do Processo Seletivo'),
    'parametros_feedback_02_help': _(u'Ao Remover o Candidato do Processo Seletivo (Envio de E-mail Somente ao Candidato Removido do Processo Seletivo)'),
    'parametros_feedback_03_lbl': _(u'Configuração de Mensagem de Feedback para o Processo de Fechamento Total da Vaga'),
    'parametros_feedback_03_help': _(u'Ao Fechar a Vaga Totalmente (Envio de E-mail Somente para os Candidatos não Aprovados)'),
    'parametros_feedback_04_lbl': _(u'Configuração de Mensagem de Feedback para o Processo de Fechamento Parcial da Vaga'),
    'parametros_feedback_04_help': _(u'Ao Fechar a Vaga Parcialmente (Envio de E-mail Somente para os Candidatos não Aprovados)'),
    'parametros_feedback_06_lbl': _(u'Configuração de Mensagem de Feedback para o Processo de Suspensão da Vaga'),
    'parametros_feedback_06_help': _(u'Ao Suspender a Vaga (Envio de E-mail a Todos os Participantes do Processo Seletivo)'),
    'parametros_feedback_07_lbl': _(u'Configuração de Mensagem de Feedback para o Processo de Reabertura da Vaga'),
    'parametros_feedback_07_help': _(u'Ao Reabrir uma Vaga (Envio de E-mail a Todos os Participantes do Processo Seletivo)'),
    'parametros_feedback_08_lbl': _(u'Configuração de Mensagem de Feedback para o Processo de Divulgação de Vagas Automáticas'),
    'parametros_feedback_08_help': _(u'Divulgação de Vagas Automáticas (Envio de E-mail Somente para os Candidatos que Desejam Receber Informações Sobre Novas Vagas.)'),
    'parametros_feedback_09_lbl': _(u'Configuração de Mensagem de Convocação de teste'),
    'parametros_feedback_09_help': _(u'Envio de E-mail para a Convocação dos Candidatos para Responderem os Testes da Vaga'),
    'parametros_feedback_10_lbl': _(u'Configuração de Mensagem de Feedback para o Processo de Remoção da Fila de Candidatura'),
    'parametros_feedback_10_help': _(u'Ao Remover o Candidato da Fila de Candidatura\n(Envio de E-mail Somente ao Candidato Removido da Fila de Candidatura)'),
    'parametros_feedback_respselecao_lbl': _(u'Configuração de Mensagem de Notificação para o Processo de Candidatura'),
    'parametros_feedback_respselecao_help': _(u'O Responsável pela Seleção da Vaga Receberá a Notificação das Candidaturas de suas Vagas Quando o Candidato se Candidatar às Mesmas'),
    'parametros_feedback_validacao': _(u'É necessário preencher todos os campos para ativar a configuração de mensagem.'),
    'parametros_listagens': _(u'Parâmetros das Listagens'),
    'parametros_modulos': _(u'Parâmetros dos Módulos'),
    'parametros_sistema': _(u'Parâmetros do Sistema'),
    'parametros_sistema_descricao': _(u'Edite e Gerencie as Configurações do Sistema.'),
    'parametros_sistema_sucesso': _(u'Parâmetros do Sistema salvo com sucesso.'),
    'parametros_textos':_(u'Parametros de Textos'),

    'parecer': _(u'Parecer'),
    'parecer_nenhum': _(u'Nenhum parecer cadastrado.'),
    'parecer_candidato': _(u'Parecer do Candidato'),
    'parecer_candidato_nao_encontrado': _(u'O Parecer do Candidato não foi encontrado.'),
    'parecer_candidato_sucesso': _(u"O Parecer do Candidato foi salvo com sucesso."),
    'pareceres_candidato': _(u'Pareceres do Candidato'),
    'parecer_cliente': _(u'Parecer do Cliente'),
    'pareceres_cliente': _(u'Pareceres do Cliente'),
    'parecer_todos': _(u'Todos os Pareceres'),
    'parecer_ultimo': _(u'O Último Parecer'),
    'parecer_ultimo_candidato': _(u'Parecer do Candidato (Último Parecer)'),
    'parecer_cliente': _(u'Parecer do Cliente'),
    'parceiro': _(u'Parceiro'),
    'parceiros': _(u'Parceiros'),
    'parceiros_ancorarh': _(u'Parceiros AncoraRh'),
    'parceiros_ancorarh_analise': _(u'Analise de Parceiros AncoraRh'),
    'partic_processo_seletivo': _(u'Partic. do Proc. Seletivo'),
    'participa_selecao': _(u'Participa da Seleção'),
    'participante_processo_seletivo': _(u'Participante do Processo Seletivo'),
    'participantes_processo_seletivo': _(u'Participantes do Processo Seletivo'),

    'pdf': _(u'PDF'),

    'pesquisa_candidato': _(u'Pesquisa de Candidato'),
    'pesquisa_cliente': _(u'Pesquisa de Cliente'),
    'pesquisa_usuario': _(u'Pesquisa de Usuário'),
    'pesquisa_vaga': _(u'Pesquisa de Vaga'),
    'percentual_vale': _(u'Percentual do Vale'),
    'periculosidade': _(u'Periculosidade'),
    'perfil': _(u'Perfil'),
    'perfil_candidato': _(u'Perfil do Candidato'),
    'perfil_cliente': _(u'Perfil do Cliente'),
    'perfil_geral': _(u'Perfil Geral'),
    'perfil_profissional': _(u'Perfil Profissional'),
    'perfil_selecao': _(u'Perfil de Seleção'),
    'perfil_selecao_candidatos': _(u'Perfil de Seleção de Candidatos'),
    'perfis_selecao_candidatos': _(u'Perfis de Seleção de Candidatos'),
    'perfil_usuario': _(u'Perfil de Usuário'),
    'pergunta': _(u'Pergunta'),
    'periodo': _(u'Periodo'),
    'permissao_ip': _(u'Permissão por IP'),
    'permissoes': _(u'Permissões'),
    'permissoes_concedidas': _(u'Permissões Concedidas'),
    'permissoes_concedidas_sucesso': _(u'Permissões Concedidas com Sucesso'),
    'permissoes_consultar': _(u'Consultar Permissões de Acesso'),
    'permissoes_gerenciar': _(u'Gerenciar Permissões de Acesso'),
    'permissoes': _(u'Permissões'),
    'permissoes_ativadas': _(u'Permissões Ativadas'),
    'permissoes_desativadas': _(u'Permissões Desativadas'),
    'permissoes_salvas': _(u"As permissões foram salvas com sucesso."),
    'pessoas_com_deficiencia': _(u'Pessoas com Deficiência'),
    'pessoa_dependente': _(u'Esta pessoa é dependente'),
    'peso': _(u'Peso'),
    'peso_valido': _(u'Peso inválido.'),
    'peso_minimo': _(u"Peso Mínimo"),
    'peso_minimo_menor_peso_maximo': _(u'O Peso Mínimo deve ser menor que o Peso Máximo.'),
    'peso_maximo': _(u"Peso Máximo"),

    'pis': _(u'PIS'),

    'plano_contrato': _(u'Plano de Contratação (Mil)'),

    'ponto_referencia': _(u'Ponto de Referência'),
    'possui_alguma_deficiencia': _(u'Possui Alguma Deficiência'),
    'possui_carro': _(u'Possui Carro'),
    'possui_moto': _(u'Possui Moto'),
    'por_nivel': _(u'Por Nível'),
    'por_tempo': _(u'Por Tempo'),
    'portal': _(u'Portal'),
    'portais_candidato': _(u'Portais do Candidato'),
    'portal_candidato': _(u'Portal do Candidato'),
    'portal_cliente': _(u'Portal do Cliente'),
    'portal_cli_visivel_help_text': _(u"Selecione abaixo quais informações/ processos complementares aparecerão nos Detalhes do Candidato na Seleção Automática de Candidatos."),
    'portal_padrao': _(u'Portal Padrão?'),
    'porte_cliente': _(u'Porte do Cliente'),
    'portecliente_duplicado':_(u"Já existe um Porte do Cliente com essa descrição."),
    'portecliente_nao_encontrado': _(u'O Porte do Cliente não foi encontrado.'),
    'portecliente_sucesso': _(u"O Porte do Cliente foi salvo com sucesso."),
    'poupanca': _(u'Poupança'),

    'prazo': _(u'Prazo'),
    'premium': _(u'Premium'),
    'pretencao_selarial': _(u'Pretensão Salarial'),
    'primeira_ocorrencia': _(u'Primeira Ocorrência do Cliente'),
    'prioridade': _(u'Prioridade'),
    'processo_salvo': _(u'Processo salvo com sucesso.'),
    'producao': _(u'Produção'),
    'produto': _(u'Produto'),
    'produto_status': _(u'Status do Produto'),
    'produto_cliente': _(u'Produto que o Cliente Consome'),
    'produtocliente_duplicado': _(u"Já existe um Produto que o Cliente Consome com essa descrição."),
    'produtocliente_nao_encontrado': _(u'O Produto que o Cliente Consome não foi encontrado.'),
    'produtocliente_n_preenchidos': _(u'Existem produtos não preenchidos. Para adicionar outros, preencha primeiro os adicionados.'),
    'produtocliente_sucesso': _(u"O Produto que o Cliente Consome foi salvo com sucesso."),
    'processos': _(u'Processos'),
    'processo_especial': _(u'Processo Especial'),
    'proc_seletivo': _(u'Proc. Seletivo'),
    'processo_seletivo': _(u'Processo Seletivo'),
    'processos_seletivos': _(u'Processos Seletivos'),
    'processo_seletivo_dados': _(u'Dados do Processos Seletivos'),
    'processo_seletivo_sucesso': _(u"O Processo Seletivo foi salvo com sucesso."),
    'processo_seletivo_nao_encontrado': _(u"O Processo Seletivo não foi encontrado."),
    'processo_seletivo_nao_salvo': _(u"O Processo Seletivo não foi salvo. Processo seletivo não encontrado."),
    'processo_seletivo_adicionar_confirm': _(u"Deseja Realmente adicionar o candidato no Processo Seletivo?"),
    'processo_seletivo_adicionar_sucesso': _(u"O Candidato foi adicionado no Processo Seletivo com sucesso."),
    'processo_seletivo_ja_adicionado': _(u"O Candidato já esta no Processo Seletivo."),
    'profissoes_funcoes': _(u'Profissões/ Funções'),
    'promotor': _(u'Promotor'),
    'promotor1': _(u'Promotor 1'),
    'promotor2': _(u'Promotor 2'),
    'promotor_cliente': _(u'Promotor do Cliente'),
    'promotor_cliente_historico': _(u'Histórico de Promotores do Cliente'),
    'promotor_igual': _(u'Este usuário já é o Promotor do Cliente.'),
    'promotor_alterado': _(u'Promotor alterado com sucesso.'),
    'proposta': _(u'Proposta'),
    'propostas': _(u'Propostas'),
    'proposta_cliente_sucesso': _(u'A Proposta do Cliente foi salva com sucesso.'),
    'proposta_cliente_nao_encontrada': _(u'A Proposta do Cliente não foi encontrada.'),
    'proposta_cliente_duplicado':_(u"A Proposta escolhida já foi salva para esse Cliente."),
    'propostas_servicos': _(u'Propostas e Serviços'),
    'propostas_servicos_transfer': _(u'Transferir Serviço'),
    'proximo': _(u'Próximo'),
    
    'publicada': _(u'Publicada'),
    'publicar': _(u'Publicar'),
    'publicar_vaga': _(u'Publicar a Vaga'),
    'publicar_vagas': _(u'Publicar Vagas'),
    'publicar_vaga_parceiros': _(u'Publicação de Vagas - Parceiros da Leme Tecnologia')
}
