from django.utils.translation import ugettext as _

textos_s = {
    'sabado': _(u'Sábado'),
    'sair': _(u'Sair'),
    'salario': _(u'Salário'),
    'salario_desejado': _(u'Salário Desejado'),
    'salario_desejado_inicial': _(u'Salário Desejado Inicial'),
    'salario_desejado_final': _(u'Salário Desejado Final'),
    'salario_maximo': _(u'Salário Máximo'),
    'salario_minimo': _(u'Salário Mínimo'),
    'salario_minimo_menor_salario_maximo': _(u'O Salário Mínimo deve ser menor que o Salário Máximo.'),
    'salario_n_informado': _(u'Salário não Informado'),
    'salvar': _(u'Salvar'),
    'salvar_continuar': _(u'Salvar e Continuar'),
    'salvar_integrante': _(u'Salvar Integrante'),
    'salvar_selecao': _(u'Salvar Seleção'),
    'salvar_recorte': _(u'Salvar Recorte'),
    'salvar_observacao': _(u'Salvar Observação'),
    'secao_eleitoral': _(u'Seção Eleitoral'),
    'segunda': _(u'Segunda'),
    'selecao_automatica': _(u'Seleção Automática'),
    'selecao_automatica_candidato': _(u'Seleção Automática de Candidato'),
    'selecao_candidatos': _(u'Seleção de Candidatos'),
    'selecao_candidatos_descricao': _(u'Realize consultas na base de dados dos candidatos.'),
    'selecao_candidatos_descricao_bne': _(u'Realize consultas de candidatos na base de dados do BNE.'),
    'selecao_candidatos_descricao_achaempregos': _(u'Realize consultas de candidatos na base de dados do Achaempregos.'),
    'selecao_candidatos_vaga_requerida_detalhes': _(u'Para ter acesso as opções de processo seletivo, retorne aos filtros de seleção e defina uma vaga.'),
    'selecao_salva': _(u'Seleção Salva'),
    'selecao_salva_carregar': _(u'Carregar Seleção Salva'),
    'selecao_salva_sucesso': _(u'Seleção salva com sucesso.'),
    'selecao_salva_trocar': _(u'Deseja realmente trocar para esta Seleção Salva? Caso não tenha salvo a seleção atual, irá perder o progresso.'),
    'selecoes_salvas': _(u'Seleções Salvas'),
    'selecionador': _(u'Selecionador'),
    'selecionador2': _(u'Selecionador(a)'),
    'selecionador_email': _(u'E-mail do Selecionador'),
    'selecionado': _(u'Selecionado'),
    'selecionados': _(u'Selecionados'),
    'selecionada': _(u'Selecionada'),
    'selecionadas': _(u'Selecionadas'),
    'selecionador_responsavel': _(u'Selecionador Responsável'),
    'selecionar_arquivo': _(u'Selecionar Arquivo'),
    'selecionar_vaga': _(u'Selecionar para a Vaga'),
    'selecionando': _(u'Selecionando...'),
    'selecione_estado': _(u'Selecione um estado para carregar as cidades'),
    'selecione_um_candidato': _(u'Selecione pelo menos um candidato.'),
    'serie': _(u'Série'),
    'sem_experiencia': _(u'Sem Experiência'),
    'sem_candidato_filtro': _(u'Sem candidatos para os filtros'),
    'sem_informacao': _(u'Sem Informação'),
    'semana': _(u'Semana'),
    'semanas': _(u'Semanas'),
    'semestre': _(u'Semestre'),
    'sem_aviso': _(u'Sem Aviso'),
    'sem_compromissos': _(u'Sem Compromissos'),
    'sem_registros_relatorio': _(u'Sem registros para o relatório.'),
    'senha': _(u'Senha'),
    'senha_portal': _(u'Senha do Portal'),
    'senha_caracteres_invalidos': _(u'A senha não deve conter caracteres especiais e acentuação.'),
    'senha_n_conferem':_(u'A Senha e a Confirmação não conferem."'),
    'senha_infojobs_invalida': _(u'Senha Infojobs inválida'),
    'senha_sms_invalida': _(u'Senha SMS inválida'),
    'senha_atual': _(u'Senha Atual'),
    'senha_troca_sucesso': _(u'Troca de Senha realizada com sucesso.'),
    'senha_salva_sucesso': _(u'Senha salva com sucesso.'),
    'servico': _(u'Serviço'),
    'servicos': _(u'Serviços'),
    'servico_cliente_nao_encontrado': _(u'O Serviço do Cliente não foi encontrado.'),
    'servico_cliente_sucesso': _(u'O Serviço do Cliente foi salvo com sucesso.'),
    'setembro': _(u'Setembro'),
    'setor': _(u'Setor'),
    'seu_cadastro_foi_salvo': _(u'Seu Cadastro foi salvo com sucesso.'),
    'sexo': _(u'Sexo'),
    'sexta': _(u'Sexta'),
    'show_link_portalcliente': _(u'Mostrar acesso do Portal do Cliente na Home'),
    'sigla': _(u'Sigla'),
    'seguro_acidente': _(u'Seguro de Acidente de Trabalho'),
    'sim': _(u'Sim'),
    'simplificado': _(u'Simplificado'),
    'sistema': _(u'Sistema'),
    'sistema_produzido_por': _(u'Este sistema foi produzido por'),
    'sistema_bloqueado': _(u'''O Sistema esta Bloqueado, entre em contato com a Leme Consultoria para obter mais informações.
    '''),
    'sistema_bloqueado_alerta': _(u'''O Sistema será bloqueado em breve, entre em contato com a Leme Consultoria para obter mais informações.
    '''),
    'site': _(u'Site'),
    'situacao': _(u'Situação'),
    'sobre': _(u'Sobre'),
    'sobre_descricao': _(u'Informações do Software SPA da sua empresa.'),
    'sobrenome': _(u'Sobrenome'),
    'solicitante': _(u'Solicitante'),
    'solicitacao_comparecimento': _(u'Solicitação de Comparecimento'),
    'somente_usuarios_cadastrados_bne': _(u'''Somente usuários de empresas
        cadastrados no BNE tem acesso à API.'''),
    'sql': _(u'Sql'),
    'sms': _(u'Mensagem de SMS'),
    'smss': _(u'Mensagens de SMS'),
    'sms_historico': _(u'Histórico de SMS'),
    'sms_historicos': _(u'Históricos de SMS'),
    'sms_duplicado': _(u"Já existe um SMS com essa mensagem."),
    'sms_nao_encontrado': _(u'O SMS não foi encontrado.'),
    'sms_sucesso': _(u"O SMS foi salvo com sucesso."),
    'sms_fornecedor': _(u"Fornecedor de SMS"),
    'sms_leme_fornecedor': _(u"Fornecedor de SMS da Leme Consultoria"),
    'status': _(u'Status'),
    'status_cliente': _(u'Status do Cliente'),
    'status_vaga': _(u'Status da Vaga'),
    'statuscliente_duplicado': _(u"Já existe um Status do Cliente com essa descrição."),
    'statuscliente_nao_encontrado': _(u'O Status do Cliente não foi encontrado.'),
    'statuscliente_sucesso': _(u"O Status do Cliente foi salvo com sucesso."),
    'status_ativo': _(u'Ativo'),
    'status_alerta': _(u'Alerta de Bloqueio'),
    'status_bloqueio': _(u'Bloqueio'),
    'storage': _('Storage (GB)'),
    'storage_qtde': _('Quantidade de Storage'),
    'super_usuario': _(u'Super Usuário'),
    'suspensas': _(u'Suspensas'),
    'sus_conjuge':_(u'SUS Cônjuge'),
}
