from django.utils.translation import ugettext as _

textos_t = {
    'tabela_categoria_habilitacao': _(u'Tabelas/CategoriasHabilitacao'),
    'tabela_cidade': _(u'Tabelas/Cidades'),
    'tabela_deficiencias': _(u'Tabelas/Deficiencias'),
    'tabela_escolaridades': _(u'Tabelas/Escolaridades'),
    'tabela_estados_civis': _(u'Tabelas/EstadosCivis'),
    'tabela_funcoes': _(u'Tabelas/Funcoes'),
    'tabela_idiomas': _(u'Tabelas/Idiomas'),
    'tabela_tipos_veiculos': _(u'Tabelas/TiposVeiculos'),
    'tabela_racas': _(u'Tabelas/Racas'),
    'tamanho_vest': _(u'Tamanho de Vestuário'),
    'tamanhos_vest': _(u'Tamanhos de Vestuário'),
    'tamanho_camisa': _(u'Tamanho da Camisa'),
    'tamanho_calsa': _(u'Tamanho da Calça'),
    'tamanho_sapato': _(u'Tamanho do Sapato'),
    'tamanho_sapato_inicial': _(u'Tamanho do Sapato Inicial'),
    'tamanho_sapato_final': _(u'Tamanho do Sapato Final'),
    'tamanhovestuario_duplicado': _(u"Já existe um Tamanho de Vestuário com essa descrição."),
    'tamanhovestuario_nao_encontrado': _(u'O Tamanho de Vestuário não foi encontrado.'),
    'tamanhovestuario_sucesso': _(u"O Tamanho de Vestuário foi salvo com sucesso."),
    'taxa': _(u'Taxa'),
    'taxa_cliente_nao_encontrada': _(u'A Taxa do Cliente não foi encontrada.'),
    'taxa_cliente_sucesso': _(u'A Taxa do Cliente foi salva com sucesso.'),
    'taxavaga_cliente_nao_encontrada': _(u'A Taxa da Vaga do Cliente não foi encontrada.'),
    'taxavaga_cliente_sucesso': _(u'A Taxa da Vaga do Cliente foi salva com sucesso.'),
    'taxa%': _(u'Taxa (%)'),
    'taxas': _(u'Taxas'),
    'taxa_padrao': _(u"Taxa Padrão"),
    'taxas_vaga': _(u'Taxas da Vaga'),
    'taxas_vaga_editar': _(u'Editar o Valor da Taxa'),

    'tela': _('Tela'),
    'telefone': _(u'Telefone'),
    'telefone1': _(u'Telefone 1'),
    'telefone2': _(u'Telefone 2'),
    'telefone_rec': _(u'Telefone para Recado'),
    'tema': _(u'Tema'),
    'tema_sistema': _(u'Tema do Sistema'),
    'tempo': _(u'Tempo'),
    'tempo_mm_ss': _(u'Tempo (MM:SS)'),
    'tempo_experiencia': _(u'Tempo/ Nível de Experiência'),
    'tempos_experiencia': _(u'Tempos/ Níveis de Experiência'),
    'tempo_limite': _(u'Tempo limite da conexão expirou. Aperte F5 para atualizar a tela e fetuar o login'),
    'teste': _(u'Teste'),
    'teste_online': _(u'Teste Online'),
    'testes_online': _(u'Testes Online'),
    'testes_online_com_foto': _(u'Testes online com Foto'),
    'testes_online_duplicado': _(u"Já existe um Teste online com essa descrição."),
    'testes_online_sucesso': _(u"O Teste online foi salvo com sucesso."),
    'testes_online_nao_encontrado': _(u'O Teste online não foi encontrado.'),
    'terca': _(u'Terça'),
    'termino_data_hora': _(u'Término (Data / Hora)'),
    'termo_responsabilidade': _(u'Termo de Responsabilidade'),
    'termo_responsabilidade_alerta': _(u"Para efetuar o cadastro e utilizar os serviços deste portal o usuário deve estar de acordo com o termo de responsabilidade ativando o campo 'Eu li e aceitei os termos e condições.'"),
    'termo_responsabilidade_abrir':  _(u'Abrir o Termo de Responsabilidade'),
    'termo_responsabilidade_fechar':  _(u'Fechar o Termo de Responsabilidade'),
    'termo_responsabilidade_aceitar':  _(u'Aceitar o Termo de Responsabilidade'),
    'termo_responsabilidade_sucesso':  _(u'Termo de Responsabilidade aceito com sucesso.'),
    'termo_uso_imagem': _(u'Termo de Uso de Imagem'),
    'termo_uso_imagem_remover_alerta_edicao': _(u'Deseja realmente remover o aceite do Termo de Uso de Imagem? Todas as suas fotos cadastradas serão removidas.'),
    'termo_uso_imagem_remover_alerta_cadastro': _(u'Deseja realmente remover o aceite do Termo de Uso de Imagem? As foto que você tenha vinculado não serão salvas.'),
    'termina_em': _(u'Termina em'),
    'termine_de_preencher': _(u'Seus dados foram salvos com sucesso, complete seu cadastro com as demais informações solicitadas e aumente suas chances em nossos processos seletivos.'),
    'texto_anuncio_vaga': _('Não são permitidos anúncios que solicitem comprovação do tempo de experiência ou façam referência a idade, gênero, raça, religião, condições de saúde, sexo, situação familiar, estado de gravidez, opinião política, nacionalidade, origem social ou qualquer outra forma de discriminação, salvo quando a natureza da atividade a ser exercida assim o exigir.'),
    'texto_acessibilidade': _(u'Texto de Acessibilidade'),
    'texto_acessibilidade_help_text': _(u'Redija neste campo um texto curto descrevendo a imagem do banner. Esta informação será utilizada por Leitores de Tela visando acessibilidade para Deficientes Visuais.'),

    'tipo': _(u'Tipo'),
    'tipo_arquivo': _(u'Tipo do Arquivo'),
    'tipo_candidato': _(u'Tipo de Candidato'),
    'tipo_candidato_bne': _(u'Tipo de Candidato Bne'),
    'tipo_candidato_duplicado':_(u"Já existe um Tipo de Candidato com essa descrição."),
    'tipo_candidato_duplicado_sigla': _(u"Já existe um Tipo de Candidato com essa sigla."),
    'tipo_candidato_sucesso': _(u"O Tipo de Candidato foi salvo com sucesso."),
    'tipo_contrato': _(u'Tipo de Contratação'),
    'tipo_cliente': _(u'Tipo de Cliente'),
    'tipo_conta': _(u'Tipo da Conta'),
    'tipo_deficiencia': _(u'Tipo de Deficiência'),
    'tipo_deficiencias': _(u'Tipos de Deficiência'),
    'tipo_documento': _(u'Tipo de Documento'),
    'tipo_documento_impressao': _(u'Tipo de Documento para Impressão'),
    'tipo_impressao': _(u'Tipo de Impressão'),
    'tipo_experiencia':_(u'Tipo de Experiência'),
    'tipo_experiencia_funcao':_(u'Tipo de Experiência na Função'),
    'tipo_exportacao':_(u'Tipo de Exportação'),
    'tipo_lancamento':_(u'Tipo de Lançamento'),
    'tipo_perfil': _(u'Tipo de Perfil'),
    'tipo_perfil_resumido': _(u'Perfil Resumido do Cliente'),
    'tipo_perfil_completo': _(u'Perfil Completo do Cliente'),
    'tipo_perfil_resumido_vaga': _(u'Perfil Resumido da Vaga'),
    'tipo_perfil_completo_vaga': _(u'Perfil Completo da Vaga'),
    'tipo_resposta': _(u'Tipo de Resposta'),
    'tipocliente_duplicado': _(u"Já existe um Tipo de Cliente com essa descrição."),
    'tipocliente_nao_encontrado': _(u'O Tipo de Cliente não foi encontrado.'),
    'tipocliente_sucesso': _(u"O Tipo de Cliente foi salvo com sucesso."),
    'tipocandidato_nao_encontrado': _(u'O Tipo de Candidato não foi encontrado.'),
    'tipo_documento': _(u'Tipo de Documento'),
    'tipo_documentos': _(u'Tipos de Documento'),
    'tipo_deficiencia': _(u'Tipo de Deficiência'),
    'tipodocumento_duplicado': _(u"Já existe um Tipo de Documento com essa descrição."),
    'tipodocumento_nao_encontrado': _(u'O Tipo de Documento não foi encontrado.'),
    'tipodocumento_sucesso': _(u"O Tipo de Documento foi salvo com sucesso."),
    'tipo_impressao':_(u'Tipo de Impressão'),
    'tipo_proposta_serv': _(u'Tipo (Propostas/Serviços)'),
    'tipo_tempo': _(u'Tipo de limite de tempo'),
    'tipo_vaga': _(u'Tipo de Vaga'),
    'tipo_vagas': _(u'Tipos de Vaga'),
    'tipo_vaga_duplicado': _(u"Já existe um Tipo de Vaga com essa descrição."),
    'tipo_vaga_nao_encontrado': _(u'O Tipo de Vaga não foi encontrado.'),
    'tipo_vaga_sucesso': _(u"O Tipo de Vaga foi salvo com sucesso."),
    'tipo_vestuario': _(u"Tipo de Vestuário"),
    'tipo_veiculo': _(u"Tipo de Veículo"),
    'tipo_salario':_(u'Tipo de Salário'),
    'tipo_senha':_(u'Tipo de Senha'),
    'tipo_senha_config': _(u'Configuração de Tipo de Senha'),
    'titulo': _(u'Título'),
    'titulo_eleitor': _(u'Título Eleitor'),
    'tirar_foto': _(u'Tirar Foto'),
    'tirar_foto_wc': _(u'Tirar Foto pela WebCam'),

    'token' : _(u'Token'),
    'token_n_encontrado': _(u'Token não encontrado'),
    'token_expirado': _(u'Token de Acesso expirado. Favor entrar em contato com o Administrador do Sistema.'),
    'token_invalido': _(u'Token de Acesso inválido. Favor entrar em contato com o Administrador do Sistema.'),
    'token_senha_salva_sucesso': _(u'Senha salva com sucesso. Efetue o Login com o acesso recém criado.'),
    'todos' : _(u'Todos'),
    'total_faturamento': _(u'Total do Faturamento'),
    'total_salario' : _(u'Total do Salário'),

    'trabalhada_por': _('Trabalhada por'),
    'trabalhar_outra_cidade': _(u'Trabalhar em outra cidade'),
    'trabalhando' : _(u'Trabalhando'),
    'trabalho' : _(u'Trabalho'),
    'trabalho_atual' : _(u'Trabalho Atual'),
    'trans_informacao': _(u'Transferência de Informações'),
    'trans_informacao_confirmacao': _(u'Deseja realmente realizar a Transferência de Informações do registro em "De" para o "Para"? Esta ação não poderá ser desfeita.'),
    'trans_informacao_sucesso': _(u'Transferência de Informações realizada com sucesso.'),
    'trans_informacao_info': _(u'Transfira todas as informações relacionadas de um registro para outro do mesmo tipo.'),
    'trans_informacao_selecao': _(u'Selecione um tipo de registro para transferir'),
    'transferir': _(u'Transferir'),
    'transferir_servico': _(u'Transferir para Serviço'),
    'transferir_servico_sucesso': _(u'Transferir para Serviço realizado com sucesso'),
    'trocar_cliente': _(u'Trocar Cliente'),
    'trocar_senha': _(u'Trocar Senha'),

}
