# -*- coding:utf-8 -*-
from django.utils.translation import ugettext as _

textos_v = {
    'vaga': _(u'Vaga'),
    'vagas': _(u'Vagas'),
    'vagas_emprego': _(u'Vagas de Emprego'),
    'vaga_aceita': _(u'Vaga aceita'),
    'vaga_anexo_sucesso': _(u'O Anexo do Perfil da Vaga foi salvo com sucesso.'),
    'vaga_com_status_nao_permitido': _(u'Você não tem permissão para realizar Manutenção em vagas com este status.'),
    'vaga_confidencial': _(u'Vaga Confidencial'),
    'vaga_deficiencia': _('Vaga para Portadores de Deficiência'),
    'vaga_esta_fechada': _(u'A Vaga está fechada.'),
    'vaga_perfil': _(u'Perfil da Vaga'),
    'vaga_nao_encontrada': _(u'A Vaga não foi encontrada.'),
    'vaga_urgente': _(u'Vaga Urgente'),
    'vagas_aberto': _(u'Vagas em Aberto'),
    'vagas_aberto_ult_10': _(u'Vagas em Aberto (Últimas 10)'),
    'vagas_aberto_ult_20': _(u'Vagas em Aberto (Últimas 20)'),
    'vagas_aberto_descricao': _(u'Consulta as Vagas em Aberto no sistema.'),
    'vagas_cliente': _(u'Vagas do Cliente'),
    'vagas_cliente_descricao': _(u'Consulte as Vagas dos Clientes.'),
    'vagas_fechadas': _(u'Vagas Fechadas'),
    'vaga_fechada_sucesso': _(u'Vaga fechada com sucesso.'),
    'vagas_filial': _(u'Filial da Vaga'),
    'vagas_recentes': _(u'Vagas mais Recentes'),
    'vagas_requisitadas': _(u'Vagas Requisitadas'),
    'vagas_requisitadas_rejeitar_confirm': _(u"Deseja realmente rejeitar a Requisição da Vaga?"),
    'vagas_requisitadas_rejeitar_sucesso': _(u"A Requisição da Vaga foi rejeitada com sucesso."),
    'vagas_sem_encaminhamentos': _(u'Vagas sem Encaminhamentos'),
    'vagas_solicitadas': _(u'Vagas Solicitadas'),
    'vagas_status': _(u'Status da Vaga'),
    'vagas_tipo': _(u'Tipo da Vaga'),
    'vagas_trabalhada_por': _(u'Trabalhada Por'),
    'vagasxcliente': _(u'Vagas x Cliente'),
    'vagasxstatus': _(u'Vagas x Status'),
    'validade_cnh': _(u'Validade (CNH)'),
    'validade_visto': _(u'Validade do Visto'),
    'valor': _(u'Valor'),
    'valor_faturamento': _(u'Valor do Faturamento'),
    'valor_salario': _(u'Valor do Salário'),
    'valor_beneficio': _(u"Valor do Benefício"),
    'valor_taxa':_(u'Valor da Taxa'),
    'valor_barra_taxa':_(u'Valor/ Taxa'),
    'ver_candidato': _(u"Ver Candidato"),
    'ver_cliente': _(u"Ver Cliente"),
    'ver_detalhe': _(u"Ver Detalhe"),
    'ver_imagem': _(u'Ver Imagem'),
    'ver_vaga': _(u"Ver Vaga"),
    'ver_botao_acesso': _(u"Deseja visualizar o botão 'Acesso - Sistema' na Página inicial (Home) ?"),
    'ver_botao_acesso_help_text': _(u"Configuração do botão 'Acesso - Sistema'"),
    'ver_mais': _(u'Ver mais'),
    'ver_mais_clientes': _(u'Ver mais Clientes'),
    'ver_mais_vagas': _(u'Ver mais Vagas'),
    'ver_portais': _(u'Ver Portais'),
    'ver_recrutadores': _(u'Ver Recrutadores'),
    'ver_respostas': _(u'Ver Respostas'),
    'ver_vagas_anunciante': _(u'Ver Vagas do Anunciante'),
    'versao': _(u'Versão'),
    'video': _(u'Vídeo'),
    'vip': _(u'Vip'),
    'vip_nao': _(u'Não Vip'),
    'visual': _(u'Visual'),
    'visualizar': _(u'Visualizar'),
    'visualizar_arquivos_exportados': _(u'Para visualizar o arquivo com os dados exportados, clique em "OK".'),
    'voce_ja_candidatou': _(u'Você já se candidatou à Vaga'),
    'voltar': _('Voltar'),
    'voltar_selecao': _('Voltar aos Filtros de Seleção'),
    'voltar_listagem': _('Voltar para Listagem'),
    'voltar_listagem_candidato': _('Voltar Listagem de Candidato'),
    'voltar_listagem_cliente': _('Voltar Listagem de Cliente'),
    'voltar_listagem_vaga': _('Voltar Listagem de Perfil da Vaga'),
    'voltar_cadastro_candidato': _('Voltar Cadastro de Candidato'),
    'voltar_cadastro_cliente': _('Voltar Cadastro de Cliente'),
    'voltar_cadastro_vaga': _('Voltar Cadastro de Perfil da Vaga'),
    'voltar_parametros': _('Voltar Parâmetros do Sistema'),
    'volume': _('Volume'),
}
